apply plugin: 'java-library'
description = 'Event Listener Impl'
dependencies {
  api project(':eldritch-horror-core:event-queue:event-queue-read')
  api project(':eldritch-horror-core:service:service-interface')
  api project(':eldritch-horror-core:model:model-read')
  api 'ch.qos.reload4j:reload4j:1.2.26'
}
