package sk.sivak.eldritchhorror.core.view.components.combat;

import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.math.MathUtils;
import sk.sivak.eldritchhorror.core.view.assetmanager.CustomAssetManager;
import sk.sivak.eldritchhorror.core.view.utils.FastForwardAction;

/** Combat cues (fireballs and monster tokens), generated by tools/generate_combat_sounds.py. */
public final class CombatSounds {

    private CombatSounds() {
    }

    public static void playFireballLaunch() {
        play(CustomAssetManager.FIREBALL_LAUNCH_SOUND, 0.40f, 0.06f);
    }

    public static void playFireballImpact() {
        play(CustomAssetManager.FIREBALL_IMPACT_SOUND, 0.50f, 0.06f);
    }

    /** Monster Horror / Damage icon scorched by a fireball. */
    public static void playMonsterTokenHit() {
        play(CustomAssetManager.MONSTER_TOKEN_HIT_SOUND, 0.50f, 0.04f);
    }

    /** Monster Health token lifting out of its bar. */
    public static void playMonsterHealthLeave() {
        play(CustomAssetManager.MONSTER_HEALTH_LEAVE_SOUND, 0.50f, 0.03f);
    }

    /** Monster Health token torn in half. */
    public static void playMonsterHealthTear() {
        play(CustomAssetManager.MONSTER_HEALTH_TEAR_SOUND, 0.60f, 0.03f);
    }

    private static void play(String path, float volume, float pitchSpread) {
        // Fast-forward shrinks the animations to a few frames; skip the cue instead of stacking it.
        if (FastForwardAction.isOn()) {
            return;
        }
        Sound sound = CustomAssetManager.getLoadedSound(path);
        if (sound == null) {
            sound = CustomAssetManager.getSound(path);
        }
        // Slight random pitch so several fireballs in a row don't sound identical.
        sk.sivak.eldritchhorror.core.view.utils.SoundPlayer.play(sound, volume, MathUtils.random(1f - pitchSpread, 1f + pitchSpread), 0f);
    }
}
