1.flavor=The Silver Twilight Lodge members ask you several riddles to prove your knowledge.
# Test Lore+1
1.pass.flavor=They instruct you in their ways.
1.pass.info=[#GOOD]Gain one Spell[]

2.flavor=Inside Ye Olde Magick Shoppe, Miriam Beecher talks to you about the finer points of the occult.
#Test Lore
2.pass.flavor=You impress her with your acumen, and she gives you a rare text.
2.pass.info=[#GOOD]Gain one Incantation Spell[]
2.fail.flavor=You lose track of time and can't seem to remember when you departed.
2.fail.info=[#BAD]Gain an Amnesia Condition[]

3.flavor=An anonymous patient in the asylum pleads with you to share what you've learned.
3.question=[#BAD]Spend one Clue[] to share what you know?
3.pass.flavor=The man begins chanting in a long-dead language.
3.pass.info=[#GOOD]Gain one Incantation Spell[]

4.flavor=Some ritual had been performed in the Black Cave, but the cultists are long gone. You look around for anything they may have left behind.
#Test Observation
4.pass.flavor=You find a scrap of parchment.
4.pass.info=[#GOOD]Gain one Incantation Spell[]
4.fail.flavor=You stumble around in the dark.
4.fail.info=[#BAD]Lose one Health[]

5.flavor=In the restricted section of Miskatonic University's library, you study an esoteric tome.
5.info=[#GOOD]Gain one Incantation Spell[]
5.flavor.2=You try to decode a note written in the margin.
#Test Lore
5.fail.flavor=The words put strange visions into your mind.
5.fail.info=[#BAD]Gain a Hallucinations Condition[]

6.flavor=During the night, you have a nightmare about the old witch, Keziah Mason. In the dream, she shares her power with you.
6.info=[#GOOD]Gain one Incantation Spell[]
6.flavor.2=When you wake up, you fear that the old witch will someday ask you for a favor in return
#Test Will+1
6.fail.info=[#BAD]Gain a Paranoia condition[]

7.flavor=Ma Mathison shows you a journal left behind by one of the lodgers at her boarding house. The text makes several oblique references to the occult, but you think you can decipher its meaning.
#Test Lore-1
7.pass.flavor=You determine the lodger's true intent.
7.pass.info.1=[#GOOD]Gain one Incantation Spell[]
7.pass.info.2=[#GOOD]Spawn one Clue[]

8.flavor=A fortune teller in Independence Square warns you of dire events. You try to interpret her words.
#Test Lore
8.pass.flavor=You discern that you ultimately survive.
8.pass.info=[#GOOD]Gain a Blessed Condition[]
8.fail.flavor=You fear an inevitable doom.
8.fail.info=[#BAD]Gain a Paranoia condition[]

9.flavor=The administrators of Arkham's Historical Society take great pains to show you their extensive collection of historical documents.
9.question=[#BAD]Become Delayed[] to [#GOOD]Gain two Spells[]?

10.flavor=Arcane rituals take place regularly in the nearby woods. You hope to uncover secrets left behind by the cult.
#Test Observation
10.pass.info=[#GOOD]Gain one Incantation Spell[]
10.fail.flavor=You trigger a protective ward.
10.fail.info=[#BAD]A Monster ambushes you![]

11.flavor=One of the stained glass windows in the South Church features an angel reading strange runes from a scroll. The runes look familiar to you.
#Test Lore
11.pass.info=[#GOOD]Gain one Incantation Spell[]
11.fail.flavor=You cannot interpret the runes, but the angel's face has a more inhuman aspect now.
11.fail.info=[#BAD]Lose two Sanity[]

12.flavor=You try to gain access to an experiment at the University's Science Building.
#Test Influence-1
12.pass.flavor=The experiment provides knowledge of worlds beyond.
12.pass.info=[#GOOD]Gain a Plumb the Void Spell[]
12.fail.flavor=You sneak in but get caught in the experiment.
12.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

13.flavor=You are suddenly confronted on Meadow Hill by an unnamable presence! The sight of the creature horrifies you beyond description.
#Test Will
13.pass.flavor=It imparts strange knowledge to you
13.pass.info=[#GOOD]Gain one Incantation Spell[]
13.fail.flavor=You awake some time later with strange bruises
13.fail.info.1=[#BAD]Lose one Sanity[]
13.fail.info.2=[#BAD]Gain a Back Injury Condition[]

14.flavor=As Oliver Thomas is unwrapping a new acquisition for his Curiositie Shoppe, you spot a bit of writing on the wrapping paper. You attempt to decipher the strange runic figures.
#Test Lore-2
14.pass.info=[#GOOD]Gain one Incantation Spell[]

15.flavor=The Arkham Advertiser ran an expose on cult activity. You hope to stealthily look through the reporter's notes.
#Test Observation
15.pass.flavor=You spot a repeated arcane phrase.
15.pass.info=[#GOOD]Gain one Incantation Spell[]
15.fail.flavor=You are roughly kicked out to the streets.
15.fail.info.1=[#BAD]Lose one Health[]
15.fail.info.2=[#BAD]Gain a Back Injury Condition[]

16.flavor=The police ask you to examine a book they seized in a recent arrest.
#Test Lore
16.pass.info=[#GOOD]Gain one Incantation Spell[]
16.fail.flavor=The text proves to be an indecipherable mess of disturbing images.
16.fail.info.1=[#BAD]Lose one Sanity[]
16.fail.info.2=[#BAD]Gain a Hallucinations Condition[]


