1.flavor=The museums's curator shows you a unique golden jewel that was recovered from the sea. You believe that the symbols on it indicate that something is hidden inside.
#Test Lore+1
1.pass.flavor=You reveal a small scroll.
1.pass.info=[#GOOD]Gain one Spell[]
1.fail.flavor=You damage the jewel and must pay for the repairs.
1.fail.info=[#BAD]Gain a Debt Condition[]

2.flavor=An old woman warns you that you've angered Yig and teaches you a protective chant.
2.info=[#GOOD]Gain one Ritual Spell[]
2.flavor.2=Concerned that she may be right, you learn all you can about Yig.
#Test Lore
2.fail.flavor=You learn nothing
2.fail.info=[#BAD]Gain a Paranoia Condition[]

3.flavor=A student has been studying the university's copy of the Necronomicon and is eager to share what he's learned in exchange for hearing what you know.
3.question=[#BAD]Spend one Clue[] to [#GOOD]Gain one Ritual Spell[]

4.flavor=You sneak aboard a ship loaded with stolen antiquities, including an ancient stone tablet. You read it.
4.info=[#GOOD]Gain one Ritual Spell[]
4.flavor.2=Memorizing the words, you feel yourself slipping into a trance.
#Test Will
4.fail.flavor=You wake up imprisoned for theft.
4.fail.info=[#BAD]Gain a Detained Condition[]

5.flavor=In an ancient underground chamber, you study strange scientific and magic paraphernalia once used by the Serpent Men.
#Test Lore
5.pass.flavor=You manipulate the devices to transform yourself.
5.pass.info=[#GOOD]Gain a Blessed Condition[]
5.fail.flavor=The devices remain utterly alien.
5.fail.info=[#BAD]Lose two Sanity[]


6.flavor=You sneak into the temple and overhear the rough croaking of deep ones chanting.
#Test Lore
6.pass.flavor=You recognize familiar elements to the words they are intoning.
6.pass.info=[#GOOD]Gain one Ritual Spell[]
6.fail.flavor=It's nothing more than horrific noise.
6.fail.info=[#BAD]Lose one Sanity[]

7.flavor=At the hospital you find a bald, old man with leathery skin and a flat face. He speaks very slowly, but his story is fascinating.
7.question=[#BAD]Become Delayed[] to listen to him?
7.pass.flavor=He recounts all the details of his time worshiping the Father of Serpents.
7.pass.info=[#GOOD]Gain two Spells[]

8.flavor=A copy of the Necronomicon is kept at the University of Buenos Aires, but the librarian tells you that it's not available for viewing at this time. You try to convince him of the book's importance.
#Test Influence
8.pass.flavor=He relents and allows you a brief look at the book.
8.pass.info=[#GOOD]Gain one Ritual Spell[]

9.flavor=The subway car stops, and you hear the sound of hissing voices in the dark.
#Test Observation -1
9.pass.flavor=You discern the phrases being whispered.
9.pass.info=[#GOOD]Gain one Ritual Spell[]
9.fail.flavor=The voices haunt you even after the lights are restored.
9.fail.info=[#BAD]Gain a Hallucinations Condition[]

10.flavor=You visit the University's former librarian and find that he owns many ancient parchments and scrolls.
#Test Lore-1
10.pass.info=[#GOOD]Gain two Spells[]
10.fail.flavor=You discover a terrible set of runes.
10.fail.info=[#BAD]Discard half of your Spells[]

11.flavor=A well-dressed man is browsing for antique books. Something about him seems strange.
#Test Observation
11.pass.flavor=You see that he's one of the serpent people in disguise.
11.pass.info.1=[#BAD]Lose one Sanity[]
11.pass.info.2=[#GOOD]Gain one Clue[]
11.fail.flavor=His identity remains a mystery.
11.fail.info.1=[#BAD]Lose one Sanity[]
11.fail.info.2=[#BAD]Gain a Paranoia Condition[]

12.flavor=The King in Yellow is being performed at the Cervantes Theatre. The play seems to infect your mind.
#Test Will
12.pass.flavor=You commit a key passage of the script to memory.
12.pass.info=[#GOOD]Gain one Ritual Spell[]
12.fail.flavor=Madness seizes you.
12.fail.info.1=[#BAD]Lose one Sanity[]
12.fail.info.2=[#BAD]Gain a Paranoia Condition[]

13.flavor=You hear the sad tale of Rufina who died after her beloved was unfaithful. Riddled with guilt, her lover used dark magic to bring her back from death. You search for signs of the spell he used.
#Test Observation-1
13.pass.info=[#GOOD]Gain a Healing Words Spell[]
13.fail.flavor=You hear her voice from beyond
13.fail.info=[#BAD]Lose one Sanity[]

14.flavor=You discover a dying serpent person. There's evidence that deep ones interrogated it. The creature repeats a strange phrase.
#Test Lore-1
14.pass.info.1=[#GOOD]Gain one Clue[]
14.pass.info.2=[#GOOD]Gain one Ritual Spell[]
14.fail.flavor=The creature's dying words hinder your thoughts.
14.fail.info.1=[#BAD]Lose one Sanity[]
14.fail.info.2=[#BAD]Discard one Spell[]

15.flavor=You find a hidden altar to Dagon. The police are eager to destroy the shrine, so you quickly study the sigils before they're removed.
#Test Lore
15.pass.info=[#GOOD]Gain one Ritual Spell[]
15.fail.flavor=You have a sudden, terrible vision of drowning.
15.fail.info=[#BAD]Lose two Sanity[]

16.flavor=The cult left their sacrifice to die in a pit of scorpions.
16.question=[#BAD]Gain a Poisoned Condition[] to save him?
16.pass.flavor=He recalls the ritual in detail.
16.pass.info=[#GOOD]Gain a Poison Mist Spell[]
16.fail.flavor=He is buried under the crawling mass.
16.fail.info=[#BAD]Lose two Sanity[]