1.flavor=You see a horrid apparition slowly ascending the stairs and have the immediate impulse to run away.
#Test Will
1.pass.flavor=You discover that it wants only to take revenge on the murderous cultists for all of their victims.
1.pass.info=[#GOOD]Improve Influence[]
1.fail.flavor=You are overcome by terror.
1.fail.info=[#BAD]Gain a Madness Condition[]

2.flavor=The British Ambassador, Sir Douglas Rutherford, begs for your help. His child has been abducted by the Brothers of the Skin.
2.question=[#BAD]Spend one Clue[] to find the cultists?
2.pass.flavor=You recover the boy.
2.pass.info=[#GOOD]Improve Influence[]

3.flavor=Members of the Turkish parliament offer you help in exchange for clearing a group of cultists out of the Shunned Mosque.
3.info=[#GOOD]Improve Influence[]
3.flavor.2=Inside, you interrupt a ritual and must resist the effect of its magical energies.
#Test Will
3.fail.flavor=Your skin writhes across your body. 
3.fail.info=[#BAD]Lose two Health[]

4.flavor=Inside the loud hustle and bustle of the Grand Bazaar, you negotiate to find a skilled instructor to tutor you.
#Test Influence-1
4.pass.info=[#GOOD]Improve one Skill of your choice[]
4.fail.flavor=The instructor teaches you nothing. Pay for his lessons.
4.fail.info=[#BAD]Gain a Debt Condition[]

5.flavor=People from every walk of life can be found enjoying the cleansing steam of the Turkish baths. Inside, you'll eventually find an expert in any given field.
5.question=[#BAD]Become Delayed[] to [#GOOD]Improve one Skill of your choice[]?


6.flavor=Professor Azap at the Topkapi Museum is not easily impressed. Only serious scholars can earn his respect.
#Test Lore
6.pass.flavor=He offers you any help the institute can provide.
6.pass.info=[#GOOD]Improve Influence[]

7.flavor=A secret group of scholars has taken an interest in you.
7.info=[#GOOD]Improve Influence[]
7.flavor.2=They show you a shocking, ancient text written by Theodorus Philetas regarding his translation of the Necronomicon. His words deeply disturb you.
#Test WILL
7.fail.info=[#BAD]Lose two Sanity[]

8.flavor=You suspect that you are being followed. You use a reflective window to watch the people walking behind you.
#Test Observation
8.pass.flavor=You spot someone stalking you and escape into a mosque, and the imam there prays for your safety.
8.pass.info=[#GOOD]Gain a Blessed Condition[]
8.fail.flavor=The assassin finds you first.
8.fail.info=[#BAD]Gain a Back Injury Condition[]

9.flavor=You decide to look into rumors of a conspiracy and soon uncover a plot to assassinate Mustafa Kemal. You gather evidence to make your case.
#Test Observation-1
9.pass.flavor=The government is extremely grateful.
9.pass.info=[#GOOD]Improve Influence[]
9.fail.flavor=The conspirators catch you and attack.
9.fail.info=[#BAD]Gain a Leg Injury Condition[]

10.flavor=Experts from all over the world pour into the city from the Orient Express. At the station, you look for a tutor willing to help you.
#Test Influence-1
10.pass.flavor=You find the ideal teacher.
10.pass.info=[#GOOD]Improve one Skill of your choice[]
10.fail.flavor=Your time is wasted.
10.fail.info=[#BAD]Become Delayed[]

11.flavor=As you sleep, your path to the Dreamlands is blocked by nightmarish visions.
#Test Will-1
11.pass.flavor=You dream of living out your entire life.
11.pass.info=[#GOOD]Improve one Skill of your choice[]
11.fail.flavor=You step off the path.
11.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

12.flavor=You defend a young scribe being attacked by an angry mob.
#Test Strength
12.pass.flavor=The man offers to introduce you to many important politicians.
12.pass.info=[#GOOD]Improve Influence[]
12.fail.flavor=The mob beats you quite badly.
12.fail.info.1=[#BAD]Lose one Health[]
12.fail.info.2=[#BAD]Gain an Internal Injury Condition[]

13.flavor=Sweeping changes to the recently formed Republic of Turkey's educational system are taking place. In exchange for your specialized knowledge, you can be taught any number of topics.
13.question=[#BAD]Spend one Clue[] to\n[#GOOD]Improve one Skill of your choice[]?

14.flavor=A stolen treasure was hidden under the city during the Crusades. Using your knowledge of the area, you think you can find it.
#Test Lore-1
14.pass.flavor=You discover a lost fortune.
14.pass.info=[#GOOD]Improve Influence[]
14.fail.flavor=Toxic fumes in the tunnels overpower you.
14.fail.info=[#BAD]Gain a Poisoned Condition[]

15.flavor=You find a crude carvings of a worm-like creature in a nearby cave. The image seems familiar.
#Test Lore
15.pass.flavor=You identify it as Shudde-M'ell.
15.pass.info=[#GOOD]Gain one Clue[]
15.fail.flavor=The disturbing image haunts your thoughts.
15.fail.info.1=[#BAD]Lose one Sanity[]
15.fail.info.2=[#BAD]Gain a Paranoia Condition[]

16.flavor=You search crates of antique books until you are exhausted.
#Test Will
16.pass.flavor=You find the Oracle of Leo the Wise, a priceless collection of prophecies.
16.pass.info=[#GOOD]Improve Influence[]
16.fail.flavor=You lose something of yours in on of the crates.
16.fail.info=[#BAD]Discard one Item or Trinket possession[]