1.flavor=In exchange for a generous donation, the Penhew Foundation will happily show the results of its global explorations.
1.question=[#BAD]Gain a Debt Condition[] to [#GOOD]Gain two Clues[]?

2.flavor=Impulsively, you look through the inspector's files while his back is turned. 
2.info=[#GOOD]Spawn one Clue on a space of your choice[]
2.flavor.2=Unfortunately, he sees you, and you'll need to fight your way out of Scotland Yard.
#Test Strength
2.fail.flavor=There is not shortage of police to arrest you.
2.fail.info=[#BAD]Gain a Detained Condition[]

3.flavor=You meet an eccentric painter in Soho who offers to show you his work. Amid his bizarre, alien landscapes, you notice some familiar details.
#Test Observation
3.pass.info=[#GOOD]Spawn one Clue on a space of your choice[]
3.fail.flavor=You see nothing but horrors.
3.fail.info=[#BAD]Lose one Sanity[]

4.flavor=The Silver Twilight Lodge is locked up tight. You look over the old building for a possible entrance.
#Test Observation
4.pass.flavor=The Lodge members are delighted by your ingenuity and offer their favor.
4.pass.info=[#GOOD]Gain a Blessed Condition[]
4.fail.flavor=You waste fruitless hours searching.
4.fail.info=[#BAD]Become Delayed[]

5.flavor=Inside the Herefordshire Asylum, a patient asks you if you've seen the Yellow Sign. You listen to his story of the King in Yellow.
#Test Observation
5.pass.info=[#GOOD]Spawn two Clues[]
5.fail.flavor=The gibberish imprints itself onto your subconscious.
5.fail.info=[#BAD]Gain a Hallucinations Condition[]

6.flavor=You peruse The Scoop, a tabloid paper that specializes in strange and lurid stories.
#Test Observation-1
6.pass.flavor=You find a vital bit of information.
6.pass.info=[#GOOD]Gain one Clue[]

7.flavor=At the lecture of a noted archaeologist, he reveals startling information!
7.info=[#GOOD]Spawn two Clues[]
7.flavor.2=During the presentation, a stranger tries to sneak a scarab into your pocket. It is inscribed with the words, "Cursed be he who moves my body. To him shall come fire, water, and pestilence."
#Test Observation
7.fail.info=[#BAD]Gain an Internal Injury Condition[]

8.flavor=You are invited to journey down to Oxford to examine John Dee's translation of the Necronomicon.
8.question=[#BAD]Become Delayed[] to [#GOOD]Spawn two Clues[]?

9.flavor=Sir Arthur Conan Doyle tells you of his interest in spiritualism around the world. His stories sound dubious but somehow familiar.
#Test Lore-1
9.pass.flavor=You discern which tales are genuine.
9.pass.info=[#GOOD]Spawn two Clues[]
9.fail.flavor=You get sidetracked pursuing false leads.
9.fail.info=[#BAD]Become Delayed[]

10.flavor=You try to schedule a meeting with D. G. Hogarth, President of the Royal Geographical Society.
#Test Influence
10.pass.flavor=The distinguished explorer shares his fascinating tales.
10.pass.info=[#GOOD]Spawn two Clues[]
10.fail.flavor=He doesn't understand the significance of your recent find.
10.fail.info=[#BAD]Advance Doom[]

11.flavor=The famous author Agatha Christie has disappeared! You suspect cult involvement and look into the case.
#Test Observation-1
11.pass.flavor=You find messages sent by the author from another world.
11.pass.info=[#GOOD]Spawn one Clue on each space containing a Gate[]
11.fail.flavor=Your investigation runs cold.
11.fail.info=[#BAD]Lose one Sanity[]

12.flavor=You interrupt a group of cultists about to sacrifice a large muscular man.
# A Cultist Monster ambushes you!
12.pass.flavor=The man you rescued introduces himself as "Bulldog" Drummond and tells you of his adventures.
12.pass.info=[#GOOD]Spawn one Clue[]

13.flavor=At the new Reptile House, you try to recapture a snake.
#Test Strength-1
13.pass.flavor=The herpetologists gratefully tell you about the snake's homeland.
13.pass.info.1=[#GOOD]Gain one Clue[]
13.pass.info.2=[#GOOD]Spawn one Clue on a Wilderness[]
13.fail.flavor=The snake bites you and disappears.
13.fail.info=[#BAD]Gain a Poisoned Condition[]

14.flavor=Thomas Carnacki offers to teach you some of his ghost-hunting techniques.
#Test Lore
14.pass.flavor=You learn how to build an electric pentacle.
14.pass.info=[#GOOD]Each Monster on a Clue loses one Health[]
14.fail.flavor=The poorly built device attracts bad luck.
14.fail.info=[#BAD]Gain a Cursed Condition[]

15.flavor=You search for the arcane symbols that permeate the city's architecture.
#Test Observation
15.pass.flavor=You use the city as a magical beacon.
15.pass.info=[#GOOD]Move up to two Clues to London[]
15.fail.flavor=The city's layout propels you into realms beyond.
15.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

16.flavor=The SIS detain you on charges of espionage and interrogate you at length.
#Test Will
16.pass.flavor=You pick up some information they let slip, and they encourage you to leave England.
16.pass.info.1=[#GOOD]Spawn one Clue[]
16.pass.info.2=[#GOOD]Gain one Ship Ticket[]
16.fail.info.1=[#BAD]Lose one Sanity[]
16.fail.info.2=[#BAD]Gain a Detained Condition[]