1.city.flavor=You search for insight into what the Order of the Death's Head was doing before they left the city.
#Test Observation
1.city.pass.flavor=You find notes about a creature.
1.city.pass.info.1=[#GOOD]Gain this Clue[]
1.city.pass.info.2=[#GOOD]Discard one Monster[]
1.city.fail.info=[#BAD]Doom advances[]

1.wilderness.flavor=The moon is full, and a satyr-like creature pulls itself from an undulating mass of sludge.
# A Goat Spawn ambushes you!
1.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
1.wilderness.pass.info.2=[#GOOD]Gain one Clue[]
1.wilderness.fail.flavor=You wake up the next morning with no memory of how you survived.
1.wilderness.fail.info=[#BAD]Gain an Amnesia Condition[]

1.sea.flavor=You search the ship for a creature that's been attacking the crew.
#Test Observation-1
1.sea.pass.flavor=You find the beast asleep in the cargo hold and easily overpower it.
1.sea.pass.info.1=[#GOOD]Gain this Clue[]
1.sea.pass.info.2=[#GOOD]Gain one Clue[]
1.sea.fail.flavor=It finds you.
1.sea.fail.info=[#BAD]A Monster ambushes you![]

2.city.flavor=You've captured one of the Brotherhood's knights. These assassins are rarely captured alive, and this may be your only chance to interrogate one.
#Test Observation
2.city.pass.flavor=You question him briefly before he swallows a poison capsule.
2.city.pass.info=[#GOOD]Gain this Clue[]
2.city.fail.flavor=He struggles and escapes.
2.city.fail.info=[#BAD]Lose two Health[]

2.wilderness.flavor=The cultists weave through the trees, making it hard to follow them.
#Test Observation-1
2.wilderness.pass.flavor=You watch their ritual.
2.wilderness.pass.info=[#GOOD]Gain this Clue[]
2.wilderness.fail.flavor=You get lost in the forest.
2.wilderness.fail.info=[#BAD]Dark Young Monster (or other Monster)\nis spawned here and you encounter it[]

2.sea.flavor=You negotiate with the crew to fight on your behalf.
#Test Influence-1
2.sea.pass.flavor=They eagerly offer their help.
2.sea.pass.info.1=[#GOOD]Gain this Clue[]
2.sea.pass.info.2=[#GOOD]Discard one Monster[]

3.city.flavor=A midnight break-in at the museum has left several guards dead. Based on descriptions of the stolen items, you try to identify what was taken.
#Test Observation
3.city.pass.flavor=You recognize the items as the legendary Furnace of Yeb and Torch of Nug.
3.city.pass.info=[#GOOD]Gain this Clue[]

3.wilderness.flavor=The faces of the robed figures are hidden behind wooden goat masks. Their chanting corrupts your thoughts.
3.wilderness.question=[#BAD]Gain a Dark Pact[] to\n[#GOOD]gain this Clue[] and [#GOOD]improve Strength[]?
3.wilderness.fail.flavor=You find yourself alone, unsure if the cultist were really there.
3.wilderness.fail.info=[#BAD]Gain a Paranoia Condition[]

3.sea.flavor=One of the crew secretly worships the Black Goat, and he has set the ship on fire. You race to fight the flames.
#Test Strength-1
3.sea.pass.flavor=You question the cultist.
3.sea.pass.info.1=[#GOOD]Gain this Clue[]
3.sea.pass.info.2=[#GOOD]Gain one Clue[]
3.sea.fail.flavor=You have to abandon ship.
3.sea.fail.info.1=[#BAD]Move to the nearest Wilderness[]
3.sea.fail.info.2=[#BAD]Become Delayed[]

4.city.flavor=In your nightmare, the chanting of the Cult of the Black Goat threatens your sanity.
#Test Will
4.city.pass.flavor=You remember the words when you wake up.
4.city.pass.info=[#GOOD]Gain this Clue[]
4.city.fail.flavor=You find yourself in an open field the next morning.
4.city.fail.info.1=[#BAD]Move to the nearest Wilderness[]
4.city.fail.info.2=[#BAD]Gain an Amnesia Condition[]

4.wilderness.flavor=This area has been prepared for a sacrifice. You keep an eye out for the Cult to return.
#Test Observation-1
4.wilderness.pass.flavor=You watch them sacrifice a goat to Shub-Niggurath.
4.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
4.wilderness.pass.info.2=[#GOOD]Gain one Clue[]
4.wilderness.fail.flavor=They surprise you in the night.
4.wilderness.fail.info.1=[#BAD]Discard one Ally[]
4.wilderness.fail.info.2=[#BAD]Lose two Sanity[]

4.sea.flavor=You stop to examine a ship that has run aground.
#Test Observation-1
4.sea.pass.flavor=The captain's journal describes a creature that was kept in the cargo hold.
4.sea.pass.info.1=[#GOOD]Gain this Clue[]
4.sea.pass.info.2=[#GOOD]Gain one Clue[]
4.sea.fail.flavor=You find nothing useful.
4.sea.fail.info=[#BAD]Clue moves to the nearest Wilderness[]

5.city.flavor=You search an underground temple dedicated to a fertility goddess.
#Test Observation-1
5.city.pass.flavor=You find a hidden tunnel that connects the temple to a cemetery.
5.city.pass.info.1=[#GOOD]Gain this Clue[]
5.city.pass.info.2=[#GOOD]Gain one Clue[]
5.city.fail.flavor=Mold and spores get into your lungs.
5.city.fail.info=[#BAD]Gain an Internal Injury Condition[]

5.wilderness.flavor=The hooded figure hands youa chalice, but you are suspicious of its contents.
#Test Observation-1
5.wilderness.pass.flavor=You pour the foul substance on the ground and study the effect.
5.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
5.wilderness.pass.info.2=[#GOOD]Gain one Clue[]
5.wilderness.fail.flavor=You drink the milk of Shub-Niggurath.
5.wilderness.fail.info=[#BAD]Dark Young monster ambushes you![]

5.sea.flavor=Under the full moon, the sailor turns into a beast. You lock him in his cabin and brace the door.
#Test Strength-1
5.sea.pass.flavor=He's normal again in the morning and tells you of his experience.
5.sea.pass.info=[#GOOD]Gain this Clue[]
5.sea.fail.flavor=He escapes and dives overboard.
5.sea.fail.info=[#BAD]Clue moves to the nearest Wilderness[]

6.city.flavor=Blood begins to drip from your ears, nose, and mouth. A witch is casting a hex against you, and you must resist it!
#Test Will
6.city.pass.flavor=You are able to send the hex somewhere else.
6.city.pass.info.1=[#GOOD]Gain this Clue[]
6.city.pass.info.2=[#GOOD]One Monster of your choice loses two Health[]
6.city.fail.info=[#BAD]Gain a Cursed Condition[]

6.wilderness.flavor=The Cult of the Black Goat has chosen you as the target of their ritual hunt. You try to cover your tracks and evade all of their traps.
#Test Observation
6.wilderness.pass.flavor=You escape with your knowledge of the Cult intact.
6.wilderness.pass.info=[#GOOD]Gain this Clue[]
6.wilderness.fail.flavor=They capture you and store you in a cage until their next ritual.
6.wilderness.fail.info=[#BAD]Gain a Detained Condition[]

6.sea.flavor=One of the sailors tells you that you've been marked and must be purified by fire. He brands your skin.
6.sea.info=[#BAD]Lose two Health[]
6.sea.flavor.2=You feel the pain break the dark influences that cling to you.
6.sea.info.2=[#GOOD]Gain this Clue[]
6.sea.info.3=[#GOOD]Discard a Cursed or Dark Pact Condition[]

7.city.flavor=You identify an important member of the local government as a worshiper of the Black Goat and try to pressure him into revealing the cult's secrets.
#Test Influence
7.city.pass.flavor=He answers your questions.
7.city.pass.info.1=[#GOOD]Gain this Clue[]
7.city.pass.info.2=[#GOOD]Gain one Clue[]
7.city.fail.flavor=He frames you for a crime.
7.city.fail.info=[#BAD]Gain a Detained Condition[]

7.wilderness.flavor=A group of cultists have been eviscerated by some creature they summoned but could not control. You think you know a way to send the abomination back where it belongs.
#Test Lore-1
7.wilderness.pass.flavor=You banish the beast.
7.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
7.wilderness.pass.info.2=[#GOOD]Retreat Doom[]
7.wilderness.fail.flavor=It throws you into a rock wall.
7.wilderness.fail.info=[#GOOD]Gain a Back Injury Condition[]

7.sea.flavor=The crew is gone, and all of the navigational equipment has been destroyed. You decide to search a nearby island.
#Test Observation
7.sea.pass.flavor=You find evidence of cult activity when you arrive.
7.sea.pass.info=[#GOOD]Gain this Clue[]
7.sea.fail.flavor=You wait for a rescue.
7.sea.fail.info=[#BAD]Become Delayed[]

8.city.flavor=As he lie dying, the bleeding priest begs you to guard the sword. He tells you Brother Tristam and his Order will stop at nothing. If you make a solemn vow, he will give you his ancient blade.
8.city.question=[#BAD]Gain a Dark Pact[] to\n[#GOOD]gain this Clue[] and\n[#GOOD]The Sword of Saint Jerome Artifact[]?

8.wilderness.flavor=The locals in a small village are celebrating an ancient pagan holiday. Some of the songs and traditions seem to have occult significance.
#Test Lore-1
8.wilderness.pass.flavor=You recognize the influence of The Black Goat and stay away from the festival.
8.wilderness.pass.info=[#GOOD]Gain this Clue[]
8.wilderness.fail.info=[#BAD]Goat Spawn Monster ambushes you![]

8.sea.flavor=You can't shake the feeling that something is hunting you. You stay awake all night to watch for the threat.
#Test Observation
8.sea.pass.flavor=You find strange tracks on the deck of the ship.
8.sea.pass.info=[#GOOD]Gain this Clue[]
8.sea.fail.info=[#BAD]A Monster ambushes you![]

9.city.flavor=The Order of the Deaths Head is engaged in a ritual. You must swear an oath of allegiance to prove that you are one of them.
9.city.question=[#BAD]Gain a Dark Pact Condition[]\nto [#GOOD]gain this Clue?[]
9.city.fail.flavor=The ritual takes place, uninterrupted.
9.city.fail.info=[#BAD]Two Monsters spawn, each on a random space[]

9.wilderness.flavor=A hermit will help you if you find the rare plants he needs.
#Test Observation
9.wilderness.pass.flavor=He cuts your hand and applies a homemade salve to the wound that causes you to feel a connection with all creatures.
9.wilderness.pass.question=[#BAD]Spend two Health[] to\n[#GOOD]deal one damage to Monsters at one location?[]
#each Monster on the chosen space loses 1 Health.

9.sea.flavor=You discover that a Pinkerton Agent who had escorted a cultist to face trial has been lured into becoming One of the Thousand.
# A Cultist Monster ambushes you! If you defeat it...
9.sea.pass.flavor=You turn them both over to the police.
9.sea.pass.info=[#GOOD]Gain this Clue[]

10.city.flavor=The zoo's night watchman shows you around after cult activity was reported there during a full moon. He soon reveals his true loyalty.
# A Cultist Monster ambushes you! If you defeat it...
10.city.pass.flavor=You search his apartment and find information about the local servants of the Black Goat.
10.city.pass.info=[#GOOD]Gain this Clue[]

10.wilderness.flavor=The cultists around the bonfire wear wooden masks that resemble some creature. You try to grab a mask in the confusion.
#Test Observation
10.wilderness.pass.flavor=You throw the mask into the fire.
10.wilderness.pass.info=[#GOOD]One Monster of your choice loses two Health[]
10.wilderness.fail.flavor=The cultists descend upon you in a frenzy.
10.wilderness.fail.info=[#BAD]Lose two Health[]

10.sea.flavor=The men with you on this island prove to be knights of the Order of the Death's Head. Now they hunt you like an animal.
#Test Observation
10.sea.pass.flavor=You return to the ship and find papers they left behind.
10.sea.pass.info=[#GOOD]Gain this Clue[]
10.sea.fail.flavor=There is no escape.
10.sea.fail.info.1=[#BAD]Lose two Health[]
10.sea.fail.info.2=[#BAD]Gain an Internal Injury Condition[]

11.city.flavor=You attend a production of The King in Yellow that features extremely intricate props.
#Test Lore-1
11.city.pass.flavor=You recognize a powerful relic and sneak in after the show to steal it.
11.city.pass.info=[#GOOD]Gain the Pallid Mask Artifact[]
11.city.fail.flavor=A knight of the Order attacks you after the show.
11.city.fail.info=[#BAD]Lose three Health[]

11.wilderness.flavor=You discover a familiar face with goat-like features.
11.wilderness.info.1=[#BAD]Discard defeated investigator[]
11.wilderness.info.2=[#BAD]Goat Spawn Monster ambushes you![]
11.wilderness.pass.flavor=You shudder to think what ritual caused this change.
11.wilderness.pass.info.1=[#BAD]Lose 1 Sanity[]
11.wilderness.pass.info.2=[#GOOD]Gain this Clue[]
11.wilderness.fail.info=[#BAD]Doom advances[]

11.sea.flavor=You board a ship that seems intact, but there's no crew. You search for an explanation.
#Test Observation-1
11.sea.pass.flavor=You find the cargo manifest contains something unspecified but labeled as highly dangerous.
11.sea.pass.info=[#GOOD]Gain this Clue[]
11.sea.fail.info=[#BAD]A Monster ambushes you![]

12.city.flavor=You do your best to convince the police that the mayor is a warlock.
#Test Influence-1
12.city.pass.flavor=They investigate and discover the necessary evidence to arrest him.
12.city.pass.info=[#GOOD]Gain this Clue[]
12.city.fail.flavor=The mayor arranges for you to have an accident.
12.city.fail.info=[#BAD]Gain a Back Injury Condition[]

12.wilderness.flavor=You examine the odd, moonlit lenses.
#Test Lore
12.wilderness.pass.flavor=You understand their purpose.
12.wilderness.pass.info=[#GOOD]Gain this Clue[]
12.wilderness.fail.flavor=An abomination appears, and one of your associates is absorbed into its horrid form.
12.wilderness.fail.info.1=[#BAD]Discard one Ally[]
12.wilderness.fail.info.2=[#BAD]Goat Spawn Monster ambushes you![]

12.sea.flavor=You find some jewelry made of human bones on the ship. Somewhere, there's a Tcho-Tcho on board!
#Test Observation-1
12.sea.pass.flavor=You find the creature hiding in the engine room.
12.sea.pass.info=[#GOOD]Gain this Clue[]
12.sea.fail.flavor=It attacks you in the night.
12.sea.fail.info=[#BAD]Lose one Health[]

13.city.flavor=According to the newspaper, the accused murderer spoke a strange phrase in French when he was arrested.
#Test Lore
13.city.pass.flavor=You recognize the passage from Cultes de Goules.
13.city.pass.info=[#GOOD]Gain this Clue[]
13.city.fail.flavor=His message reached his fellow cult members without being detected.
13.city.fail.info=[#BAD]Doom advances[]

13.wilderness.flavor=The last person to ask about cults died out here. When you reach the spot indicated by the police, you find his remains.
13.wilderness.info.1=[#GOOD]Gain this Clue[]
13.wilderness.info.2=[#BAD]Dark Young Monster (or other Monster)\nis spawned here and you encounter it[]
13.wilderness.pass.info=[#GOOD]Gain one Clue[]

13.sea.flavor=In the ship's cargo hold, you find a small carving of a horrible creature.
13.sea.info=[#BAD]Lose one Sanity[]
13.sea.flavor.2=You feel a terrible connection to the beast, a bond that threatens to kill you both.
# if investigators owns Dark Pact
13.sea.pass.info=But nothing happens.
13.sea.fail.info.1=[#GOOD]One Monster of your choice\nloses three Health[]
13.sea.fail.info.2=[#BAD]Lose three Health[]

14.city.flavor=Brother Tristam's knights are about to perform a ritual sacrifice. He tells you that he'd be willing to let the victims go, if you agree to his bargain.
14.city.question=[#BAD]Gain a Dark Pact Condition[] to [#GOOD]gain this Clue[]?
14.city.fail.flavor=The ritual proceeds.
14.city.fail.info=[#BAD]Each Monster recovers all Health[]

14.wilderness.flavor=You find the Cult of the Black Goat holding their ritual right where you suspected. However, you did not anticipate the creature they summoned.
#Monster ambushes you
14.wilderness.pass.info=[#GOOD]Gain this Clue[]
14.wilderness.fail.flavor=The victory in ritual combat feeds the strength of Shub-Niggurath.
14.wilderness.fail.info=[#BAD]Doom advances[]

14.sea.flavor=Inside the cargo hold you find a monstrosity that was being transported to an exclusive island for a hunting expedition, but now the thing has gotten loose.
#Monster ambushes you
14.sea.pass.flavor=You check the shipping manifest.
14.sea.pass.info=[#GOOD]Gain this Clue[]

15.city.flavor=A woman with goat-like features is standing over a badly wounded policeman.
15.city.info=[#BAD]Goat Spawn Monster (or other Monster)\nis spawned here and you encounter it[]
# pass will test
15.city.pass.flavor=The policeman is able to tell you what he was investigating before he dies.
15.city.pass.info=[#GOOD]Gain this Clue[]

15.wilderness.flavor=In the middle of the night, the cult of the Black Goat surrounds you and invites you to become One of the Thousand in exchange for their help.
15.wilderness.question=[#BAD]Gain a Dark Pact Condition[] to [#GOOD]gain this Clue[]?
15.wilderness.pass.info=[#GOOD]One Monster of your choice loses two Health[]

15.sea.flavor=Storm clouds loom, but you want the captain to keep moving forward.
#Test Influence-1
15.sea.pass.flavor=You find a yacht moored to the island.
15.sea.pass.info=[#GOOD]Gain this Clue[]
15.sea.fail.flavor=You try to proceed on your own, but your small boat capsizes.
15.sea.fail.info=[#BAD]Clue moves to the nearest Wilderness[]

16.city.flavor=Something about this old boarding house and it's proprietor seems strange.
#Test Observation-1
16.city.pass.flavor=You spot small glyphs carved into the woodwork throughout your room.
16.city.pass.info=[#GOOD]Gain this Clue[]
16.city.fail.flavor=You suffer a witch's hex and wake up in agony.
16.city.fail.info.1=[#BAD]Lose one Health[]
16.city.fail.info.2=[#BAD]Lose one Sanity[]

16.wilderness.flavor=You hear the pounding of hooves.
# if dark pact is owned
16.wilderness.flavor.2=The Black Goat has come to collect.
16.wilderness.info=[#BAD]Flip Dark Pact Condition.[]
16.wilderness.flavor.3=You glimpse the horrifying beast pouring from the wild like fog.
#Test Will
16.wilderness.pass.info=[#GOOD]Gain this Clue[]
16.wilderness.fail.info=[#BAD]Lose three Sanity[]

16.sea.flavor=A nightgaunt has carried a ghoul onto the deck of the ship to find you.
# ambushed by ghoul
16.sea.pass.flavor=The ghoul offers help in exchange for its life.
16.sea.pass.info.1=[#GOOD]Gain this Clue[]
16.sea.pass.info.2=[#GOOD]One investigator may\ndiscard a Cursed Condition[]