1.city.flavor=Randolph Carter claims that the Silver Twilight Lodge stole a unique family treasure. You investigate the local Lodge.
#Test Observation
1.city.pass.flavor=You gain the opportunity to examine the stolen treasure.
1.city.pass.info=[#GOOD]Gain this Clue[]
1.city.pass.question=[#BAD]Discard a Spell[] to\n[#GOOD]gain the Silver Key Artifact[]?
1.city.fail.flavor=The Lodge frames you for the theft.
1.city.fail.info=[#BAD]Gain a Detained Condition[]

1.wilderness.flavor=Talking to one of the locals, you realize that this village and its surrounding farms are inhabited by worshipers of Yog-Sothoth.
# A Cultist Monster ambushes you!
1.wilderness.pass.flavor=You manage to reach safety.
1.wilderness.pass.info=[#GOOD]Gain this Clue[]

1.sea.flavor=A strange fog covers the water, but no one else seems to see it.
#Test Observation
1.sea.pass.flavor=You find that the fog originates from a circle of stones on the beach of a small island.
1.sea.pass.info=[#GOOD]Gain this Clue[]
1.sea.fail.flavor=The mist impairs your vision.
1.sea.fail.option.1=[#BAD]Discard this Clue[]
1.sea.fail.option.2=[#BAD]Discard one Spell[]

2.city.flavor=An old man approaches you and begs you to make a solemn vow to deliver a book to his grandson, Wilbur, in a town called Dunwich.
2.city.question=[#BAD]Gain a Dark Pact Condition[] to\n-[#GOOD]Gain this Clue[]\n-[#GOOD]Gain the Necronomicon Artifact[]?
2.city.fail.info=[#BAD]Discard this Clue[]

2.wilderness.flavor=You watch several mi-go operate alien technology.
2.wilderness.info=[#GOOD]Gain this Clue[]
# If you don't have any Spell
2.wilderness.flavor.2=The mi-go are not aware of your presence.
# If you have at least 1 Spell
2.wilderness.flavor.3=Because you have at least one Spell, the mi-go are suddenly aware of your presence and turn their strange devices toward you.
#Test Will
2.wilderness.fail.flavor=Their devices erode your sense of reason.
2.wilderness.fail.info.1=[#BAD]Lose one Sanity[]
2.wilderness.fail.info.2=[#BAD]Gain a Paranoia Condition[]

2.sea.flavor=You see a white ship on the horizon, its sails apparently unaffected by the strong winds you feel racing across the waves. You use a telescope to examine the craft.
#Test Observation-1
2.sea.pass.flavor=You see the ship passing through a fog bank into another world.
2.sea.pass.info.1=[#GOOD]Gain this Clue[]
2.sea.pass.info.2=[#GOOD]Gain one Clue[]

3.city.flavor=The library has received several requests from the Whateley family for information about the Necronomicon. You tell the staff to ignore all such requests from that family.
#Test Influence-1
3.city.pass.flavor=The staff sends out a warning to other libraries.
3.city.pass.info.1=[#GOOD]Gain this Clue[]
3.city.pass.info.2=[#GOOD]Gain one Clue[]
3.city.fail.flavor=The Whateleys acquire forbidden knowledge.
3.city.fail.info=[#BAD]Doom advances[]

3.wilderness.flavor=The terrain has been flattened by some enormous creature. You follow its path of destruction.
#Test Observation
3.wilderness.pass.flavor=You find that the thing had been stored in a barn.
3.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
3.wilderness.pass.info.2=[#GOOD]Gain one Clue[]
3.wilderness.fail.flavor=All you find is mutilated animals.
3.wilderness.fail.info=[#BAD]Lose one Sanity[]

3.sea.flavor=Your ship travels through a time portal, and you hear news of future events on the radio.
3.sea.info.1=[#GOOD]Gain this Clue[]
# if a Hound of Tindalos Monster is on the game board
3.sea.info.2=[#BAD]Hound of Tindalos Monster is after you![]
# otherwise
3.sea.info.3=[#BAD]Lose one Sanity[]

4.city.flavor=You attempt to sneak into the local Silver Tiwilight Lodge.
#Test Observation
4.city.pass.flavor=You find a chart that assigns the names of wizards to seasons of the year. Sanford corresponds to Spring, Waite to Summer, Curwen to Autumn, and Eibon to Winter. You remember the information in case it someday proves useful.
4.city.pass.info.1=[#GOOD]Gain this Clue[]
4.city.pass.info.2=[#GOOD]Gain one Clue[]

4.wilderness.flavor=Local lore speaks of a place of tremendous arcane potential.
#Test Observation-1
4.wilderness.pass.flavor=You find a junction of ley lines.
4.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
4.wilderness.pass.info.2=[#GOOD]Gain one Clue[]
4.wilderness.fail.flavor=Your power is channeled for a dark purpose.
4.wilderness.fail.info.1=[#BAD]One Gate is spawned[]
4.wilderness.fail.info.2=[#BAD]Discard one Spell[]

4.sea.flavor=Sheets of luminescent colors fill the horizon. You hear a hum in the air, almost like a voice.
#Test Observation
4.sea.pass.flavor=It tells you of arcane secrets.
4.sea.pass.info.1=[#GOOD]Gain this Clue[]
4.sea.pass.info.2=[#GOOD]Gain one Spell[]
4.sea.fail.flavor=The sounds gives you a terrible headache.
4.sea.fail.info=[#BAD]Lose one Health[]

5.city.flavor=Carl Sanford, head of Arkham's Silver Twilight Lodge, has tracked you down to find out what you know about Yog-Sothoth.
#Test Influence
5.city.pass.flavor=You learn more from him than he does from you.
5.city.pass.info.1=[#GOOD]Gain this Clue[]
5.city.pass.info.2=[#GOOD]Gain one Spell[]
5.city.fail.flavor=Your knowledge aids his mysterious pursuit.
5.city.fail.info=[#BAD]One Gate is spawned[]

5.wilderness.flavor=A rumor has passed through the small communities of a witch named Lavinia. You sift through many eyewitness accounts to determine if Wilbur Whateley's mother still lives.
#Test Observation-1
5.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
5.wilderness.pass.info.2=[#GOOD]Gain one Clue[]
5.wilderness.fail.flavor=The cult of Yog-Sothoth learns of your investigation.
5.wilderness.fail.info=[#BAD]One Gate is spawned[]

5.sea.flavor=Large, winged crustaceans land on your ship and command you to join Yog-Sothoth.
5.sea.question=[#BAD]Gain a Dark Pact Condition?[]
5.sea.pass.flavor=The mi-go share their plans with you.
5.sea.pass.info.1=[#GOOD]Gain this Clue[]
5.sea.pass.info.2=[#GOOD]Gain one Clue[]
5.sea.fail.info=[#BAD]One Gate is spawned[]

6.city.flavor=You hear of a bookstore that sells extremely rare volumes, but it is in an area that is very difficult to navigate.
#Test Observation-1
6.city.pass.info.1=[#GOOD]Gain this Clue[]
6.city.pass.info.2=[#GOOD]Gain one Tome Artifact[]
6.city.fail.flavor=You get lost.
6.city.fail.info=[#BAD]Become Delayed[]

6.wilderness.flavor=You dream of being in all places and existing at all times. You know that you will wake up soon, so you use this heightened state to explore significant times and places.
# Test Lore
6.wilderness.pass.info=[#GOOD]Gain this Clue[]
6.wilderness.fail.flavor=Your memories have been changed when you wake up.
6.wilderness.fail.info=[#BAD]Gain an Amnesia Condition[]

6.sea.flavor=The captain believes that you're bad luck. You search for the true source of the ships troubles.
#Test Observation
6.sea.pass.flavor=You find a hex bag among your possessions.
6.sea.pass.info=[#GOOD]Gain this Clue[]
6.sea.fail.flavor=The ill fortune seems to follow you.
6.sea.fail.info=[#BAD]Gain a Cursed Condition[]

7.city.flavor=A noted politician walks straight toward you, glaring.
# A Cultist Monster ambushes you!
7.city.pass.flavor=You find out that he was secretly a member of the Silver Twilight Lodge.
7.city.pass.info=[#GOOD]Gain this Clue[]
7.city.fail.flavor=The magical attack leaves you deeply shaken.
7.city.fail.info=[#BAD]Gain a Paranoia Condition[]

7.wilderness.flavor=At midnight, you feel an eerie presence surrounding the stone altar at the top of the hill. This strange presence fills your mind with blasphemous secrets.
7.wilderness.info=[#GOOD]Gain this Clue[]
# If you don't have any Spell
7.wilderness.flavor.2=The entity ignores you.
# If you have at least 1 Spell
7.wilderness.flavor.3=Because you have at least one Spell, the entity tries to pull you into a deep trance.
#Test Will
7.wilderness.fail.info.1=[#BAD]Lose one Sanity[]
7.wilderness.fail.info.2=[#BAD]Become Delayed[]

7.sea.flavor=The punctures in reality have caused a terrible storm over the Ocean, but you believe you know a way to patch the rift between worlds.
# Test Lore
7.sea.pass.info=[#GOOD]Gain this Clue[]
7.sea.pass.question=[#BAD]Discard one Spell[] to\n[#GOOD]discard one Gate[]?

8.city.flavor=A distraught woman claims that her missing son struck a bargain with the Lurker at the Threshold.
# Test Observation
8.city.pass.flavor=You find the boy and try to free him from the debt.
8.city.pass.question=[#BAD]Discard one Spell[] to\n-[#GOOD]Gain this Clue[]\n-[#GOOD]Gain one Clue[]
8.city.fail.flavor=You suffer Yog-Sothoth's wrath.
8.city.fail.info.1=[#BAD]Discard this Clue[]
8.city.fail.info.2=[#BAD]Gain a Cursed Condition[]

8.wilderness.flavor=You find footprints that indicate a large number of people passed through the area. You try to follow their path.
# Test Observation-1
8.wilderness.pass.flavor=The trail leads you to an ancient stone circle inscribed with runes.
8.wilderness.pass.info.1=[#GOOD]Gain this Clue[]
8.wilderness.pass.info.2=[#GOOD]Gain one Spell[]
8.wilderness.fail.flavor=The search is long and exhausting.
8.wilderness.fail.info=[#BAD]Lose one Health[]

8.sea.flavor=The whole ship is dragged sideways across the water by an invisible force.
8.sea.info.1=[#GOOD]Gain this Clue[]
8.sea.info.2=[#BAD]Move one space toward the nearest Gate[]
8.sea.option.1=[#BAD]Lose two Sanity[]
8.sea.option.2=[#BAD]Discard one Spell[]

9.city.flavor=Wealthy recluse possesses a vast occult library. You attempt to convince his family to let you examine the books.
#Test Influence-2
9.city.pass.flavor=You obtain several significant texts.
9.city.pass.info=[#GOOD]Gain one Tome Artifact[]
9.city.fail.flavor=The recluse pays you a visit and shares his insanity.
9.city.fail.info=[#BAD]Gain a Madness Condition[]

9.wilderness.flavor=An enormous silhouette passes before you. Its appearance is indistinct unless you have the gift of magic.
# If you have at least 1 Spell, else end encounter
9.wilderness.info=[#BAD]Gain a Hallucinations Condition[]
9.wilderness.flavor.2=Those familiar with this area will probably know where the creature came from.
#Test Lore-1
9.wilderness.pass.info=[#GOOD]Gain this Clue[]

9.sea.flavor=Your time at sea has given you perspective. You haven't been able to identify Yog-Sothoth's influences because you are immersed in them. You must purge yourself of his magical "gifts".
9.sea.question=[#BAD]Discard one Spell[] to [#GOOD]gain this Clue[]?

10.city.flavor=You find a children's book containing a simple parable about Yog-Sothoth, but the message can be overlooked by those who know too much.
#Test Lore Roll 1 less die for each Spell you have.
10.city.pass.flavor=You see the hidden meaning.
10.city.pass.info=[#GOOD]Gain this Clue[]
10.city.fail.flavor=It's nonsense.
10.city.fail.info=[#BAD]Discard this Clue[]

10.wilderness.flavor=A misshapen creature staggers toward you and cries out, sounding nearly human. Your instincts tell you to run away.
#Test Will
10.wilderness.pass.flavor=It writes the name of a long-dead wizard and points to itself before dying.
10.wilderness.pass.info=[#GOOD]Gain this Clue[]
10.wilderness.fail.flavor=You leave quickly.
10.wilderness.fail.info.1=[#BAD]Lose two Sanity[]
10.wilderness.fail.info.2=[#BAD]Gain a Paranoia Condition[]

10.sea.flavor=The captain is heading for an island alone, taking some strange occult-looking items.
#Test Lore
10.sea.pass.flavor=You recognize his intent and sabotage his ritual by stealing a book from his pack.
10.sea.pass.info=[#GOOD]Gain this Clue[]
10.sea.fail.flavor=He opens a door to another world.
10.sea.fail.info=[#BAD]One Gate is spawned[]

11.city.flavor=While taking a taxi, your driver suddenly stops and leaves the car. Shortly after, a man in a black suit opens the door next to you.
#  A Cultist Monster ambushes you!
11.city.pass.flavor=You search his pockets and learn his identity.
11.city.pass.info=[#GOOD]Gain this Clue[]

11.wilderness.flavor=You were told that those who spend the night in this dilapidated cabin are never heard from again. At midnight, you see a ghostly figure gesture for you to follow it.
11.wilderness.question=[#BAD]Spend two Sanity[] and\n[#BAD]Gain a Lost in Time and Space Condition[]\nto [#GOOD]gain this Clue[]?

11.sea.flavor=A powerful wind rises from the island's cave, and you look for a place to hide.
#Test Observation-1
11.sea.pass.flavor=The large, semi-invisible creature that emerges ignores you and flies away, allowing you to search the cave.
11.sea.pass.info=[#GOOD]Gain this Clue[]
11.sea.fail.flavor=You come face-to-face with a flying polyp.
11.sea.fail.info=[#BAD]Lose one Sanity[]

12.city.flavor=John Scott agrees to answer your questions about the Silver Twilight Lodge. That night, something seems odd.
#Test Observation-1
12.city.pass.flavor=You find an arcane sigil carved behind your bed.
12.city.pass.info=[#GOOD]Gain this Clue[]
12.city.fail.flavor=You can remember nothing from your time there.
12.city.fail.info=[#BAD]Gain an Amnesia Condition[]

12.wilderness.flavor=You spot a grave marked with Silver Twilight iconography that seems familiar.
#Test Lore+1
12.wilderness.pass.flavor=You recall the location of a magical door.
12.wilderness.pass.question=[#BAD]Spawn one Gate[] to [#GOOD]open this door[]?
12.wilderness.pass.flavor.2=You find the dead man's journal.
12.wilderness.pass.info=[#GOOD]Gain this Clue[]

12.sea.flavor=Men come aboard looking for you. You stay hidden, hoping to search their belongings.
#Test Observation-1
12.sea.pass.flavor=You discover that they're members of the Silver Twilight Lodge.
12.sea.pass.info=[#GOOD]Gain this Clue[]
12.sea.fail.flavor=They find you and cast a hex to alter your memories.
12.sea.fail.info.1=[#BAD]Discard this Clue[]
12.sea.fail.info.2=[#BAD]Discard one Spell[]

13.city.flavor=A professor warns that if a gateway hasn't already been opened in the city, it will be soon. He knows exactly where the cult performs its rituals.
# If you are on a space containing a Gate
13.city.question=[#BAD]Discard one Spell[] to [#GOOD]close this Gate[]?

13.wilderness.flavor=The hermits cabin has lead pendulums in bottles that ring when magic is near. The sound is intolerable to a sane mind.
#  If you have at least one Spell, lose 2 Sanity.
13.wilderness.flavor.2=You talk to the hermit about Yog-Sothoth.
#Test Influence-1
13.wilderness.pass.info=[#GOOD]Gain this Clue[]

13.sea.flavor=Dolphins have been following the boat since you left port. You search the cargo hold for a powerful object that might attract their attention.
#Test Observation-1
13.sea.pass.flavor=You find a hidden compartment.
13.sea.pass.info.1=[#GOOD]Gain this Clue[]
13.sea.pass.info.2=[#GOOD]Gain one Magical Artifact[]
13.sea.fail.flavor=You can't sleep for the rest of the voyage.
13.sea.fail.info=[#BAD]Lose two Sanity[]

14.city.flavor=A map of ley lines across the world is for sale, but it's expensive.
#Test Influence-1
14.city.pass.flavor=You acquire this guide to the places where Yog-Sothoth's influence is strongest.
14.city.pass.info=[#GOOD]Gain this Clue[]
14.city.fail.flavor=You sell off your equipment in an attempt to afford it.
14.city.fail.info=[#BAD]Discard one Item possession[]

14.wilderness.flavor=Inside your tent, glowing orbs swarm around your head. You try to use a protective ritual, but you've forgotten how.
14.wilderness.info=[#BAD]Discard one Spell[]
14.wilderness.flavor.2=You feel your memories being stolen.
#Test Will-1
14.wilderness.pass.flavor=You escape with your remaining recollections intact.
14.wilderness.pass.info=[#GOOD]Gain this Clue[]
14.wilderness.fail.info=[#BAD]Gain an Amnesia Condition[]

14.sea.flavor=You have taken a small craft to the island but find nothing of use. You must leave at low tide and navigate through shoals to get back to the ship before it leaves.
#Test Observation-1
14.sea.fail.flavor=Your rowboat capsizes, and you have to swim back.
14.sea.fail.info.1=[#BAD]Lose one Health[]
14.sea.fail.info.2=[#BAD]Gain a Leg Injury Condition[]

15.city.flavor=A veteran of the Great War, mutilated by mustard gas, is sitting in a park talking to himself. You offer some help and ask about his experiences.
#Test Influence-1
15.city.pass.flavor=He tells you of the other worlds he saw during combat.
15.city.pass.info=[#GOOD]Gain this Clue[]

15.wilderness.flavor=In a cabin, you find mounted animal and human trophies. You need to avoid hunting traps to reach the small town nearby.
#Test Observation
15.wilderness.pass.flavor=The sheriff fills you in about this madman.
15.wilderness.pass.info=[#GOOD]Gain this Clue[]
15.wilderness.fail.flavor=You are trapped.
15.wilderness.fail.info.1=[#BAD]Lose two Sanity[]
15.wilderness.fail.info.2=[#BAD]Gain a Detained Condition[]

15.sea.flavor=The captain reveals that he's a high-ranking member of the Silver Twilight Lodge, and he suggests an unheard-of offer: an open exchange of information. You know that whatever you tell him will further the Lodge's plots.
15.sea.question=[#BAD]Advance Doom[] to [#GOOD]gain this Clue[]?

16.city.flavor=Asenath Waite seems familiar with the occult, but something about her is odd.
#Test Observation-1
16.city.pass.flavor=You believe someone is controlling her, and you learn that her father was a wizard.
16.city.pass.info=[#GOOD]Gain this Clue[]
16.city.fail.flavor=Something about the way she acts unnerves you.
16.city.fail.info=[#BAD]Gain a Paranoia Condition[]

16.wilderness.flavor=A farmer is hiding from a swarm of mi-go. You suspect a magical distraction will make it easier to sneak the farmer to safety.
#Test Observation-1 You may discard 1 Spell to reroll up to 2 dice.
16.wilderness.fail.flavor=The mi-go catch the man and remove his brain.
16.wilderness.fail.info=[#BAD]Lose two Sanity[]

16.sea.flavor=You see a vision of the Lord of the Abyss. He will grant you knowledge to keep Yog-Sothoth bound, but only if he does not sense corruption within you.
# If you have a Dark Pact Condition
16.sea.fail.flavor=He sends his nightgaunts to take you away.
16.sea.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]
16.sea.pass.info=[#GOOD]Gain this Clue[]
