### 1 ###
1.flavor=As you approach the uncharted island, you hear the sound of a cannon and feel the deck shudder. You ship is badly damaged, and if you hope to survive, you must overpower the crew aboard the gunship "Alert", the source of the cannon fire.
#Test (Strength-1)

1.pass.flavor=Once you have control of the ship, you find that it was filled with cultist devoted to Cthulhu. You search through their notes for information about the island.
#Test (Observation-1)
1.pass.pass.flavor=You find a folder with everything you need to know.
1.pass.pass.info=[#GOOD]Advance the active Mystery[]

1.fail.flavor=The Alert's crew kill all of the sailors you were traveling with and knock you unconscious. When you wake up, you find yourself tied up in up in their makeshift brig.
1.fail.info=[#BAD]Gain a Detained Condition[]

### 2 ###
2.flavor=Enormous silhouettes of flying creatures descend from the clouds. The star spawn have arrived! They attack with blood-chilling ferocity.
#Test  (Strength-1)

2.pass.flavor=You survive their onslaught and hide yourself in a small cavern. You wait there for reprieve, listening to the terrible alien shrieks of the creatures.
#Test (Will-1)
2.pass.pass.flavor=They eventually relent.
2.pass.pass.info=[#GOOD]Advance the active Mystery[]
2.pass.fail.flavor=The noise places horrible images into your mind.
2.pass.fail.info=[#BAD]Gain a Hallucinations Condition[]

2.fail.flavor=They crush you against the stones. You have no hope of standing up against their might.
2.fail.info=[#BAD]Lose three Health[]

### 3 ###
3.flavor=You swim up to the slimy rocks and walk into the corpse city of R'lyeh. Inside, cyclopean, green, stone blocks meet at non-Euclidean angles. The very sight of this alien construction threatens to shatter your mind.
#Test (Will-1).

3.pass.flavor=Trying not to focus on the architecture, you instead take note of a series of hieroglyphics inscribed on the walls. You desperately try to interpret them for useful information.
#Test (Lore -1)
3.pass.pass.info=[#GOOD]Advance the active Mystery[]

3.fail.flavor=Your life up until this moment has been a dream from which you are just awakening. You now understand that your true purpose is to offer yourself up as sacrifice to Cthulhu.
3.fail.info=[#BAD]Lose three Sanity[]

### 4 ###
4.flavor=Hundreds of deep ones surface from the water, crawling up the green stones. You hide yourself and watch their priest perform a strange ritual.
#Test (Observation-1)

4.pass.flavor=Although you cannot understand the words, the ritual reminds you of a similar ceremony performed by human cults.
#Test (Lore-1)
4.pass.pass.flavor=You recognize the moment when they will close their eyes and take the opportunity to escape.
4.pass.pass.info=[#GOOD]Advance the active Mystery[]
4.pass.fail.flavor=You misinterpret the chant. A loud croak informs you that one of the deep ones has spotted you. The monstrous fish creatures descend upon you from all sides.
4.pass.fail.info=[#BAD]Lose three Health[]

4.fail.flavor=A loud croak informs you that one of the deep ones has spotted you. The monstrous fish creatures descend upon you from all sides.
4.fail.info=[#BAD]Lose three Health[]

### 5 ###
5.flavor=At the very peak of the island, you encounter a massive stone door featuring a horrific bas-relief of a dragon-like creature. Strange symbol are carved along the edge of the door. Some of the icons resemble drawings you've seen in books.
#Test (Lore-1)

5.pass.flavor=You spot a protective ward out of pace, hanging precariously. A member of your crew is on top of the door frame next to the ward. You warn him to carefully replace it.
#Test (Influence-1)
5.pass.pass.info=[#GOOD]Advance the active Mystery[]
5.pass.fail.flavor=He fumbles it. Somewhere on the other side of the enormous door, you hear a thunderous splashing sound and feels the ground shake as something approaches the island's surface.
5.pass.fail.info=[#BAD]Doom advances[]

5.fail.flavor=Somewhere on the other side of the enormous door, you hear a thunderous splashing sound and feels the ground shake as something approaches the island's surface.
5.fail.info=[#BAD]Doom advances[]

### 6 ###
6.flavor=You recognize the alien landscape from a dream you've had.
6.info=[#BAD]Lose one Sanity[]
6.flavor.2=You try to remember as many details as you can from the dream to navigate through the city
#Test (Observation-1)

6.pass.flavor=You make your way to a hidden chamber lined with strange glyphs carved into the stone. Some of the symbols seem familiar.
#Test (Lore-1)
6.pass.pass.flavor=You learn the story of how the elder things trapped Cthulhu in the city.
6.pass.pass.info=[#GOOD]Advance the active Mystery[]
6.pass.fail.flavor=The images fester in your subconscious.
6.pass.fail.info=[#BAD]Gain a Paranoia Condition[]

6.fail.flavor=You quickly become lost and tumble down a long stone slope.
6.fail.info=[#BAD]Gain a Leg Injury Condition[]
6.fail.flavor.2=As you climb to your feet you realize you're not alone.
6.fail.info.2=[#BAD]Spawn one Monster on your space[]

### 7 ###
7.flavor=A swarm of elder things bursts out of the water and flies over the large stone outcroppings. One of the creatures takes notice of you. It swoops out of the sky and tries to entangle you in its tendrils.
#Test (Strength-1)

7.pass.flavor=You keep the creature at bay, but several others have taken notice. You try to recall what you know of elder things.
#Test (Lore-1)
7.pass.pass.flavor=You know that they are enemies of Cthulhu, here to prevent his return, and you lie down and let them pass over you.
7.pass.pass.info=[#GOOD]Advance the active Mystery[]
7.pass.fail.flavor=You run in a panic. You are lifted into the air and thrown to the ground.
7.pass.fail.info.1=[#BAD]Gain a Back Injury Condition[]
7.pass.fail.info.2=[#BAD]Gain a Leg Injury Condition[]
7.pass.fail.info.3=[#BAD]Gain an Internal Injury Condition[]

7.fail.flavor=You are lifted into the air and thrown to the ground.
7.fail.info.1=[#BAD]Gain a Back Injury Condition[]
7.fail.info.2=[#BAD]Gain a Leg Injury Condition[]
7.fail.info.3=[#BAD]Gain an Internal Injury Condition[]

### 8 ###
8.flavor=Large tablets of black stone tower above you, each engraved with an R'lyehian, the blasphemous language of the star spawn.
#Test Lore-1

8.pass.flavor=You translate the strange symbols, used to invoke Dagon. You quickly shield your thoughts from his influence.
#Test (Will-1)
8.pass.pass.flavor=You push the alien intelligence from your mind.
8.pass.pass.info=[#GOOD]Advance the active Mystery[]
8.pass.fail.flavor=You retain control as long as you can before passing out.
8.pass.fail.info.1=[#BAD]Lose one Sanity[]
8.pass.fail.info.2=[#BAD]Become Delayed[]

8.fail.flavor=As you look at the tablets, a powerful presence invades your mind. Dagon floods your soul with corruption.
8.fail.info.1=[#BAD]Lose two Sanity[]
8.fail.info.2=[#BAD]Gain a Cursed Condition[]

