1.flavor=You discover a hidden shrine to Cybele in an ancient catacomb. It will be a long process to excavate the find, but removing such a blight from Rome's foundations will grant you a higher reward.
1.question=[#BAD]Become Delayed[] to [#GOOD]Gain a Blessed Condition[]?

2.flavor=Ever since arriving to Rome, you've had nightmares about being betrayed. You try to assure yourself that they are only dreams.
#Test Will
2.pass.flavor=The nightmares stops.
2.pass.info=[#GOOD]Improve Will[]
2.fail.flavor=The nightmares continue.
2.fail.info=[#BAD]Lose one Sanity[]

3.flavor=A group of Blackshirts are interrogating and old priest, and you try to intervene.
#Test Influence
3.pass.flavor=They let the priest go, and he is eternally grateful.
3.pass.info=[#GOOD]Gain a Blessed Condition[]
3.fail.flavor=You are shoved against a wall and arrested.
3.fail.info=[#BAD]Gain a Detained Condition[]

4.flavor=The Vatican Library is so vast! You ask a librarian for a recommendation.
#Test Influence
4.pass.flavor=He leads you to a codex that recounts how worshipers of Shub-Niggurath were driven out of Rome, and the story renews  your confidence.
4.pass.info=[#GOOD]Improve Will[]

5.flavor=You have an inspirational dream in which you are a proud Roman quaestor.
5.info=[#GOOD]Improve Will[]
5.flavor.2=Your reverie is interrupted by a band of small, primitive men running wild outside. You try to negotiate with this lost tribe of Miri Nigri.
#Test Influence
5.fail.flavor=They continue their pursuit of some ancient grudge.
5.fail.info.1=[#BAD]Lose one Health[]
5.fail.info.2=[#BAD]Lose one Sanity[]

6.flavor=You speak to a number of Vatican authorities about your investigations. They carefully consider your story.
#Test Influence-1
6.pass.flavor=You are thanked for doing good work.
6.pass.info=[#GOOD]Gain a Blessed Condition[]
6.fail.flavor=You are demoralized by their rejection.
6.fail.info.1=[#BAD]Lose one Sanity[]
6.fail.info.2=[#BAD]Discard a Blessed Condition[]

7.flavor=A witch cult must have used this villa to conduct their rituals. They've left behind a number of small potions.
7.question=Drink one to [#GOOD]Improve one Skill of your choice[]?
7.pass.flavor=You must resist the ill effects of the elixir.
#Test Will
7.fail.info=[#BAD]Gain a Cursed Condition[]

8.flavor=You are invigorated by a visit to a magnificent cathedral.
8.info=[#GOOD]Improve Will[]
8.flavor.2=In the basement, you find a mosaic depicting robed men bowing before a great fire. To your horror, it is surrounded by scorch marks that resemble human silhouettes.
#Test Will-1
8.fail.info=[#BAD]Gain a Paranoia Condition[]

9.flavor=In a hidden room beneath the Colosseum, you find an ancient creature that once fought gladiators. Somehow, the terrible beast has survived and attacks you on sight.
#Test Strength
9.fail.flavor=You are incapacitated by your wounds, and the monstrosity escapes.
9.fail.info.1=[#BAD]Lose one Health[]
9.fail.info.2=[#BAD]Gain a Leg Injury Condition[]

10.flavor=The Sistine Chapel is temporarily closed, but you attempt to sneak inside.
#Test Observation
10.pass.flavor=The breathtaking paintings and tapestries inside inspire you.
10.pass.info=[#GOOD]Improve Will[]
10.fail.flavor=You are caught and arrested
10.fail.info=[#BAD]Gain a Detained Condition[]

11.flavor=You attend a lecture by a physics professor named Enrico Fermi about the incredible power contained in atoms. You do your best to follow his theories.
#Test Lore-1
11.pass.flavor=You see a new potential for overcoming the threats to this world.
11.pass.info.1=[#GOOD]Gain one Clue[]
11.pass.info.2=[#GOOD]Improve Will[]
11.fail.flavor=You grow even more disheartened.
11.fail.info=[#BAD]Lose two Sanity[]

12.flavor=You discover the ancient recipe to create Mithridate, a powerful concoction to protect you from harm. Interpreting it as best you can, you assemble the ingredients.
#Test Lore-1
12.pass.flavor=The Mithridate works.
12.pass.info=[#GOOD]Gain a Blessed Condition[]
12.fail.flavor=The foul brew makes you sick.
12.fail.info=[#BAD]Gain a Poisoned Condition[]

13.flavor=You closely examine the ancient writing on the obelisk in the Piazza del Popolo and implore the ancient pharaohs to watch over you.
13.info=[#GOOD]Gain a Blessed Condition[]
13.flavor.2=The presence of the relic entrances you.
#Test Will-1
13.fail.flavor=You step through the obelisk into another reality.
13.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

14.flavor=A raggedy-looking man offers to trade an old coin for one of your belongings. He claims that throwing the coin into the Trevi Fountain will ensure that you will safely return to Rome.
14.question=[#BAD]Discard one Item possession[]?
14.pass.flavor=The knowledge strengthens your resolve.
14.pass.info=[#GOOD]Improve Will[]

15.flavor=In the Capuchin Crypt, you are surrounded by the bones of thousands of dead monks, arranged in strange patterns. The sight forces you to confront your own impending death.
15.question=[#BAD]Spend 2 Sanity[] to face your fears?
15.pass.flavor=You discover a new sense of destiny.
15.pass.info=[#GOOD]Gain a Blessed Condition[]

16.flavor=After an unsuccessful attempt on the life of Benito Mussolini, you observe the interrogation of the would-be assassin.
#Test Observation
16.pass.flavor=You learn much about resisting intense coercion.
16.pass.info=[#GOOD]Improve Will[]
16.fail.flavor=Their tactics are horrible to behold.
16.fail.info.1=[#BAD]Lose one Sanity[]
16.fail.info.2=[#BAD]Gain a Paranoia Condition[]
