1.flavor=You meet Hammett, a former Pinkerton Agent, on the street car and try to convince him to teach you how to be detective.
#Test Influence
1.pass.flavor=He agrees.
1.pass.info=[#GOOD]Improve Observation[]
1.fail.flavor=He's too distracted by his financial woes. You help to support his family.
1.fail.info=[#BAD]Gain a Debt Condition[]

2.flavor=While patrolling in Chinatown, you become adept at spotting signs of cult activity.
2.info=[#GOOD]Improve Observation[]
2.flavor.2=You find their temple, but must dispel a hex on the door to enter.
#Test Lore
2.fail.flavor=The hex saps your life away.
2.fail.info.1=[#BAD]Lose one Health[]
2.fail.info.2=[#BAD]Lose one Sanity[]

3.flavor=You speak to a military prisoner on Alcatraz Island. He tells you his story of deserting after encountering a horrific creature.
#Test Will
3.pass.flavor=He thanks you for believing him and blesses your name.
3.pass.info=[#GOOD]Gain a Blessed Condition[]
3.fail.flavor=The story throws you into a hysterical fit, and the guards arrest you.
3.fail.info=[#BAD]Gain a Detained Condition[]

4.flavor=You are invited to the Hearst Castle and find yourself surrounded by the best and brightest.
4.question=[#BAD]Become Delayed[] to stay for a few days?
4.pass.flavor=You pick up some amazing talents.
4.pass.info=[#GOOD]Improve one Skill of your choice[]

5.flavor=Inspector Jack Manion is looking for information about the Tongs in Chinatown. If you can help him, he'll teach you the basics of police work in exchange.
5.question=[#BAD]Spend one Clue[] to [#GOOD]Improve Observation[]?

6.flavor=You find the husk of a squid-like creature in a tunnel. Just seeing it terrifies you.
#Test Will-1
6.pass.flavor=You identify the chthonian. Scientists clamor to contribute to its study.
6.pass.info=[#GOOD]Improve one Skill of your choice[]
6.fail.flavor=You run headlong through the tunnel.
6.fail.info=[#BAD]Gain a Leg Injury Condition[]

7.flavor=A private investigator prepares you to help him on a case.
7.info=[#GOOD]Improve Observation[]
7.flavor.2=He's looking for a strangely shaped skull that's gone missing after recovered from a fire. Your investigation reveals symbols including the one for "resurrection".
#Test Lore-1
7.fail.flavor=You do not notice the symbol for "curse"
7.fail.info=[#BAD]Gain a Cursed Condition[]

8.flavor=A pulp author named Smith invites you to read his work. The stories disturb you.
#Test Will
8.pass.flavor=You gain insight into how the invisible world remains hidden.
8.pass.info=[#GOOD]Improve Observation[]
8.fail.flavor=The tale chills you to the bone.
8.fail.info=[#BAD]Gain a Madness Condition[]

9.flavor=The Examiner hires you to spend a night in the Winchester Mystery House. They provide you with experts in detecting the supernatural.
9.info=[#GOOD]Improve Observation[]
9.flavor.2=The odd architecture and the building's history threaten to unhinge your mind as the evening passes.
#Test Will-1
9.fail.info=[#BAD]Lose two Sanity[]

10.flavor=At the Tlaxcala Mining Company, you find strange records of a man who could transport himself across tremendous distances. The idea sounds absurd, but some elements of his story ring familiar.
10.question=[#BAD]Spend two Sanity[] to \n[#GOOD]move to a space of your choice[]?

11.flavor=A tall, gaunt man with a bald, skull-like head introduces himself as Surama and offers to teach you the secrets of Atlantis. However, you can sense he is trying to manipulate you as he speaks.
11.question=[#BAD]Gain a Dark Pact Condition[] to \n[#GOOD]Improve Observation[] and\n[#GOOD]Improve one Skill of your choice[]?

12.flavor=You study a fascinating book entitled Megapolisomancy which describes how to use the energy of large cities to manipulate the future.
#Test Lore
12.pass.flavor=You gain keen insight into future events.
12.pass.info=[#GOOD]Improve Observation[]
12.fail.flavor=A horrific, paranormal creature manifests in your room.
12.fail.info.1=[#BAD]Lose one Health[]
12.fail.info.2=[#BAD]Lose one Sanity[]

13.flavor=You are asked to examine a corpse. Working with the mortician, you learn some basic forensic skills.
13.info=[#GOOD]Improve Observation[]
13.flavor.2=The body has a strange wire hood over its head and seems to have been electrocuted. lt's a grisly sight.
#Test Will-1
13.fail.flavor=The image haunts your nightmares.
13.fail.info=[#BAD]Lose two Sanity[]

14.flavor=The fabric of reality is weak in the seedy Tenderloin district. As a result, many here suffer from the Black Madness. Very little of what they say can be understood.
#Test Lore-1
14.pass.flavor=You learn much.
14.pass.info=[#GOOD]Improve one Skill of your choice[]
14.fail.flavor=They drag you with them into the unknown.
14.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

15.flavor=You hear of a powerful wizard in Chinatown named Lang-Fu, who will help you if you can afford his fee.
#Test Influence-1
15.pass.flavor=He uses his sorcery to transform you
15.pass.info=[#GOOD]Improve one Skill of your choice[]
15.fail.flavor=He deems you unworthy, and several deep ones attack you.
15.fail.info.1=[#BAD]Lose one Health[]
15.fail.info.2=[#BAD]Lose one Sanity[]

16.flavor=As a stranger bumps into you, a small needle pierces your skin, infecting you with black fever. Doctor Miller oversees your recovery.
#Test Strength
16.pass.flavor=You recover and Miller teaches you to be alert to such tactics in the future.
16.pass.info=[#GOOD]Improve Observation[]
16.fail.flavor=The fever stays with you.
16.fail.info.1=[#BAD]Gain a Poisoned Condition[]
16.fail.info.2=[#BAD]Gain a Paranoia Condition[]