1.flavor=The shrine holds an abundance of ancient relics.
1.info=[#GOOD]Improve Lore[]
1.flavor.2=Your eye catches strange figures written on the ceiling. You find it hard to look away.
#Test WILL
1.fail.flavor=The writing seems to move on its own
1.fail.info=[#BAD]Gain a Hallucinations Condition[]

2.flavor=If you can convince Chu Min to help, he will use New China's vast resources to provide you with any sort of instruction you require.
#Test Influence
2.pass.info=[#GOOD]Improve one Skill of your choice[]
2.fail.flavor=His men force you out onto the street.
2.fail.info=[#BAD]Lose one Health[]

3.flavor=You search through old copies of The Shanghai Courier to find strange or unexplained stories.
#Test Observation
3.pass.flavor=You discover a pattern of arcane activity in the city.
3.pass.info=[#GOOD]Improve Lore[]
3.fail.flavor=No pattern emerges from all this horror.
3.fail.info=[#BAD]Lose one Sanity[]

4.flavor=You break into a warehouse filled with ancient wonders and learn much by studying its contents.
4.info=[#GOOD]Improve Lore[]
4.flavor.2=You must remain silent to avoid being caught.
#Test Observation
4.fail.flavor=They question you for days.
4.fail.info=[#BAD]Become Delayed[]

5.flavor=The decadent crime lord, Lin Tang-Yu, offers you access to his library of occult treasures in exchange for information.
5.question=[#BAD]Spend one Clue[] to [#GOOD]Improve Lore[]?

6.flavor=The Shanghai Museum recommends you speak to Mu Hsien, a preeminent scholar of the occult. You send him a message that you hope will convince him to help.
#Test Influence
6.pass.flavor=He shares his wealth of knowledge.
6.pass.info=[#GOOD]Improve Lore[]

7.flavor=The old man offers to make tea for you. You see him mix in a strange, green powder that he calls "tyuk".
7.question=[#BAD]Become Delayed[] to to wait for it to brew?
7.pass.flavor=The tyuk seems to heighten all of your senses.
7.pass.info=[#GOOD]Improve one Skill of your choice[]

8.flavor=You spot an odd, fish-like man pull a young monk underwater! You dive in to rescue him, holding your breath as long as you can.
#Test Strength
8.pass.flavor=The grateful monk prays over you.
8.pass.info=[#GOOD]Gain a Blessed Condition[]
8.fail.flavor=You are implicated in his disappearance.
8.fail.info=[#BAD]Gain a Detained Condition[]

9.flavor=You try to persuade a collector of Chinese antiquities to let you see the Seven Cryptical Books of Hsan.
#Test Influence
9.pass.flavor=The scrolls prove instructive.
9.pass.info=[#GOOD]Improve Lore[]
9.fail.flavor=The collector tricks you.
9.fail.info=[#BAD]Discard one Artifact or one Trinket[]

10.flavor=The Green Gang has hidden 200-years worth of stolen treasures in a large vault. Despite the risk, you try to break in.
#Test Observation
10.pass.flavor=You discover several magical texts.
10.pass.info=[#GOOD]Improve Lore[]
10.fail.flavor=You are caught and punished without mercy.
10.fail.info.1=[#BAD]Lose one Health[]
10.fail.info.2=[#BAD]Gain an Internal Injury Condition[]

11.flavor=A Taoist priest teaches you his esoteric skills.
11.info=[#GOOD]Improve Lore[]
11.flavor.2=He requests that in return, you help him combat the jiangshi.
#Test Strength-2
11.pass.flavor=You return the hopping corpses to their graves.
11.pass.info=[#GOOD]Recover two Sanity[]
11.fail.flavor=They steal some or your life force.
11.fail.info.1=[#BAD]Lose one Health[]
11.fail.info.2=[#BAD]Lose one Sanity[]

12.flavor=The Shanghai Museum asks for your help in cataloging a recent donation.
12.question=[#BAD]Become Delayed[] to help them?
12.pass.flavor=You find lost chapters from the book Zi Bu Yu that provide you with many stories of the supernatural.
12.pass.info=[#GOOD]Improve Lore[]

13.flavor=A man with a loudly ticking watch offers to help you in exchange for spying on the Communist Party.
13.question=[#BAD]Gain a Dark Pact Condition[] to\n[#GOOD]Improve one Skill of your choice[]
13.fail.flavor=The well-dressed man warns you that he's always watching.
13.fail.info=[#BAD]Gain a Paranoia Condition[]

14.flavor=An old man offers to tattoo a symbol on the palm of your hand for good luck. You accept, but the pain is overwhelming.
#Test Will-1
14.pass.info=[#GOOD]Improve one Skill of your choice[]
14.fail.flavor=You pass out and lose your memories.
14.fail.info.1=[#BAD]Lose one Health[]
14.fail.info.2=[#BAD]Gain an Amnesia Condition[]

15.flavor=As you sleep, you are drawn into the realm of dreams by the Monkey King. He tells you that a fish demon has trapped him there. You must focus to return to your body.
#Test Will-1
15.pass.flavor=The Monkey King gives you a gift.
15.pass.info=[#GOOD]Improve one Skill of your choice[]
15.fail.flavor=You cannot return home.
15.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

16.flavor=Investigating an altar to the great dragon Yinglong, you are attacked by serpent people. The only way to defend against them is to perform a powerful magical sacrifice.
16.question=[#BAD]Discard one Spell[]?
16.fail.info.1=[#BAD]Lose one Health[]
16.fail.info.2=[#BAD]Gain a Poisoned Condition[]

