1.flavor=Your money and passport have been stolen! You work on the Sydney Harbor Bridge to pay the bills. You meet the job's rigorous demands.
1.info=[#GOOD]Improve Strength[]
1.flavor.2=When your passport is found at the scene of a crime, you need to prove your innocence.
#Test Influence
1.fail.info=[#BAD]Gain a Detained Condition[]

2.flavor=A group of hunters provide you with the skills to track down a bunyip.
2.info=[#GOOD]Improve Strength[]
2.flavor.2=When you find the massive four-legged creature, your weapons cannot pierce its leathery hide. You try to protect yourself from the beast's terrible claws and teeth.
#Test Strength-1
2.fail.info=[#BAD]Lose two Health[]

3.flavor=You dream of crossing a vast desert hunted by an enormous winged creature. In the dream, you turn to face your fears.
#Test Will
3.pass.flavor=You wake up feeling more alive then ever.
3.pass.info=[#GOOD]Improve Strength[]
3.fail.flavor=The fear lingers.
3.fail.info=[#BAD]Lose one Sanity[]

4.flavor=Due to a city-wide shortage of supplies, shopkeepers won't even show you their wares unless you prove that you can pay top dollar.
# Test Influence-1
4.pass.info=[#GOOD]Gain one random Weapon from the deck[]
4.fail.flavor=You are roped into a devious scheme.
4.fail.info=[#BAD]Gain a Debt Condition[]

5.flavor=The Theosophical Society is excited to hear what knowledge you have gained during your travels.
5.question=[#BAD]Spend one Clue[]?
5.pass.flavor=They gratefully provide you with and exercise and diet regimen that fortifies your vitality.
5.pass.info=[#GOOD]Improve Strength[]

6.flavor=Several passengers on an underground train have been trapped by a tunnel collapse. The dark and claustrophobic climb through the rubble is terrifying.
#Test Will
6.pass.flavor=The nerves hold out enough to help dig a clear path for the survivors.
6.pass.info=[#GOOD]Improve Strength[]
6.fail.info=[#BAD]Lose one Sanity[]

7.flavor=An old, aboriginal man is on trial for a murder that you know he didn't commit. You agree to testify to prove his innocence.
#Test Influence
7.pass.flavor=He speaks to the spirits on your behalf.
7.pass.info=[#GOOD]Gain a Blessed Condition[]
7.fail.flavor=You are accused of perjury.
7.fail.info=[#BAD]Gain a Detained Condition[]

8.flavor=The constable sees you admire the abandoned weapon. "Give it a bit to see if anyone claims it," he says. "If not, you can help yourself."
8.question=[#BAD]Become Delayed[] to\n[#GOOD]Gain one random Weapon from the deck[]?

9.flavor=Charles Hopkins hires you to restore the suburb of Bungarribee. At night, you feel hands grab your throat!
#Test Will
9.pass.flavor=You return to the work in the morning and grow stronger.
9.pass.info=[#GOOD]Improve Strength[]
9.fail.flavor=You run away in terror.
9.fail.info.1=[#BAD]Lose one Sanity[]
9.fail.info.2=[#BAD]Gain a Hallucinations Condition[]

10.flavor=In a game of cards, the stakes are raised and you bet a prized possession. You watch the other players carefully for any tells.
#Test Observation-1
10.pass.flavor=You call a bluff.
10.pass.info=[#GOOD]Gain 1 random Weapon from the deck[]
10.fail.flavor=Another player outwits you and claims your prize.
10.fail.info=[#BAD]Discard one Item or Trinket possession[]

11.flavor=Late at night, dark young wander into the city from the surrounding wilderness. You struggle to escape from the creatures.
#Test Strength
11.fail.flavor=The attack leaves you badly wounded.
11.fail.info.1=[#BAD]Lose two Health[]
11.fail.info.2=[#BAD]Gain a Back Injury Condition[]

12.flavor=You've been caught in a bushfire. You try to find a safe path through the smoke and flames.
#Test Observation-1
12.pass.flavor=You find previously unknown speed and strength in yourself.
12.pass.info=[#GOOD]Improve Strength[]
12.fail.flavor=You need time to recover.
12.fail.info=[#BAD]Become Delayed[]

13.flavor=An armed man asks you strange questions. You suspect that he is possessed by an alien being.
13.question=[#BAD]Spend one Clue[] to answer his questions?
13.pass.flavor=He regains his senses and surrenders his weapon.
13.pass.info=[#GOOD]Gain one random Weapon from the deck[]

14.flavor=In the dream world, you are attacked by the arkaroo, sorcerers who resemble snakes. You use warding symbols to protect yourself.
#Test Lore
14.pass.flavor=You wake invigorated.
14.pass.info=[#GOOD]Improve Strength[]
14.fail.flavor=You wake feeling weak.
14.fail.info.1=[#BAD]Lose one Sanity[]
14.fail.info.2=[#BAD]Gain a Poisoned Condition[]
        
15.flavor=A young aboriginal football player named Douglas offers to teach you how to play.
15.question=[#BAD]Become Delayed[] to train with him?
15.pass.info=[#GOOD]Improve Strength[]

16.flavor=A prisoner has stolen a weapon and escaped into the bush. You hope to track him down.
#Test Observation
16.pass.flavor=You arrest him and secure his weapon.
16.pass.info=[#GOOD]Gain one random Weapon from the deck[]
16.fail.flavor=He gets the drop on you and escapes.
16.fail.info.1=[#BAD]Lose one Health[]
16.fail.info.2=[#BAD]Gain a Leg Injury Condition[]