### 1 ###
1.flavor=You can sense Yog-Sothoth in your thoughts, trying to consume your identity by filling your memories with ultimate knowledge. You struggle against the swirling energy that drags you forward, into the gate.
#Test Strength-1

1.pass.flavor=Rather than being consumed by knowledge, you repeat a chant that can allegedly purge a mind of all memories.
#Test Lore
1.pass.pass.question=[#BAD]Gain an Amnesia Condition[] to \n-[#GOOD]Advance the active Mystery[]?
1.pass.fail.info=[#BAD]Lose three Sanity[]

1.fail.flavor=You know the gate. You are the gate. You are the key and guardian of the gate. Past, present, future, all are one in you.
1.fail.info=[#BAD]You are devoured[]

### 2 ###
2.flavor=Despite the reports of the mad albino woman's death, she stands at this gate to wait for her child, the so-called Dunwich Horror, to call its father's name. As soon as she sees you, she casts a hex, and you attempt to produce a protective ward.
#Test Lore-1

2.pass.flavor=Your protective ward surprises her. You tell her that she's the last of the Whateley clan, hoping to intimidate her.
#Test Influence Roll 1 less die for each Cultist Monster on the game board (minimum 1 die)
2.pass.pass.info=[#GOOD]Advance the active Mystery[]
2.pass.fail.flavor=She recognizes your deceit.
2.pass.fail.info=[#BAD]Doom advances[]

2.fail.flavor=You know of no way to shield yourself from her powerful sorcery.
2.fail.info.1=[#BAD]Gain a Cursed Condition[]
2.fail.info.2=[#BAD]Gain a Madness Condition[]
2.fail.info.3=[#BAD]Gain an Injury Condition[]

### 3 ###
3.flavor=You see a circle of stones, each covered with magic runes. You sense that this is some sort of test of your knowledge.
#Test Lore-1

3.pass.flavor=You touch each rune in order, identifying yourself as a wizard. To your horror, you feel Yog-Sothoth taking over your mind, claiming you as its own.
#Test Will. Roll 1 less die for each Spell you have (minimum 1 die).
3.pass.pass.info=[#GOOD]Advance the active Mystery[]
3.pass.fail.info=[#BAD]Lose three Sanity[]

3.fail.flavor=Yog-Sothoth does not recognize you as a sorcerer and ejects you from the gate.
3.fail.info.1=[#BAD]Gain two Spells[]
3.fail.info.2=[#BAD]Gain a Dark Pact Condition[]

### 4 ###
4.flavor=A mass of glowing spheres, mouths, and tentacles burst forth from the portal. You feel a terrible intelligence searching your mind for signs of corruption.
# If you have a Dark Pact Condition, you are devoured.
4.flavor.2=The Lurker then fills your thoughts with forbidden knowledge.
#Test Will-1

4.pass.flavor=You exercise extreme mental discipline to regain control of your mind. By examining the images the Lurker has chosen to reveal, you believe that you can bind it between dimensions.
#Test Lore
4.pass.pass.question=[#BAD]Discard one Spell[] to \n-[#GOOD]Advance the active Mystery[]?
4.pass.fail.info=[#BAD]Lose three Sanity[]

4.fail.flavor=In one horrifying flash, your mind is flooded with knowledge of all places and all times as your molecules are torn apart.
4.fail.info=[#BAD]You are devoured[]

### 5 ###
5.flavor=Yog-Sothoth's avatar 'Umr-At-Tawil, stands before the Ultimate Gate. He is a tall figure, wrapped in gray fabric, and you can hear his thoughts thundering in your head. He warns you to proceed no further if you are afraid.
#Test Will-1

5.pass.flavor='Umr-At-Tawil guides you through the gates to encounter Yog-Sothoth.
#Test Influence You may spend any number of Clues to add 1 success to your test result. If your test result is 3 or greater
5.pass.pass.flavor=You are allowed to return home.
5.pass.pass.info=[#GOOD]Advance the active Mystery[]
5.pass.fail.flavor=Yog-Sothoth threatens to trap you on the doomed planet Yaddith.
5.pass.fail.info=[#BAD]Lose three Sanity[]

5.fail.flavor='Umr-At-Tawil holds a large metallic sphere that radiates powerful pulses of energy. The rhythmic waves shake you to your core, tearing your body to pieces.
5.fail.info=[#BAD]You are devoured[]

### 6 ###
6.flavor=Carl Sanford stands high atop a mountain in a swirling dimension of his own creation. He claims that the Silver Twilight Lodge has harnessed the power of Yog-Sothoth to transform him into a god. However, you suspect much of what you see is an illusion.
#Test Observation-1

6.pass.flavor=Hoping to catch Sanford off guard, you lunge at him.
#Test Strength. You may spend any number of Sanity to roll 1 additional die for each Sanity spent. If your test result is 3 or greater
6.pass.pass.flavor=You overpower him.
6.pass.pass.info=[#GOOD]Advance the active Mystery[]
6.pass.fail.flavor=He manages to chant an incantation.
6.pass.fail.info=[#BAD]Gain a Cursed Condition[]

6.fail.flavor=You attempt to speak to Sanford, either to reason with him or to threaten him, but all that comes out of your mouth is a ritual chant, binding you to the Silver Twilight Lodge.
6.fail.info=[#BAD]You are devoured[]

### 7 ###
7.flavor=The landscape around you changes constantly as Yog-Sothoth drags you through all worlds and all times. You search desperately for anything familiar to find your way home.
#Test Observation-1

7.pass.flavor=You sense your loved ones and mentally reach out to them for help.
#Test Influence : Roll 1 less die for each investigator that has been defeated or devoured
7.pass.pass.flavor=Your body is snapped back to reality.
7.pass.pass.info=[#GOOD]Advance the active Mystery[]
7.pass.fail.flavor=You drift further through worlds beyond.
7.pass.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]
7.fail.flavor=When your vision clears, you find yourself on a frozen plateau. For a tragically brief time, you are the only living thing in the universe.
7.fail.info=[#BAD]You are devoured[]

### 8 ###
8.flavor=You are surprised to discover the indistinct silhouette of a man on the other side of the gate. Without knowing his identity, you try to convince him to help you navigate these strange other worlds.
#Test Influence-1

8.pass.flavor=He introduces himself as Randolph Carter and offers you his Silver Key. You try to harness its power.
#Test Lore : You may gain a Dark Pact Condition to roll 3 additional dice If your test result is 3 or greater
8.pass.pass.flavor=The key works.
8.pass.pass.info=[#GOOD]Advance the active Mystery[]
8.pass.fail.flavor=You're hopelessly lost.
8.pass.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

8.fail.flavor=He introduces himself as the wizard Zkauba, and he uses his arcane powers to steal your experiences.
8.fail.info.1=[#BAD]Discard all Clues[]
8.fail.info.2=[#BAD]Discard all Spells[]
8.fail.info.3=[#BAD]Discard all Improvements[]

