1.flavor=You find a gem bearing the symbol of the Emerald Lama. In its facets, you see the image of some horrible beast. Suddenly, the creature is right next to you!
1.info=Choose one non-Epic Monster and move it to your space, then encounter it.

2.flavor=You are off the coast of Okinawa.
2.question=[#BAD]Become Delayed[] to explore some submerged pyramids?
2.pass.flavor=You discover ancient writing that claims to "harm one's enemies".
2.pass.info=[#GOOD]One Monster of your choice\nloses three Health[]

3.flavor=You ask the enigmatic Dragon Lords to rid the world of potential threats to Japan.
#Test Influence
3.pass.flavor=The mysterious group casts their spells.
3.pass.info=[#GOOD]Each Monster on a space of your choice\nloses two Health[]
3.fail.flavor=The Dragon Lords lash out at you.
3.fail.info=[#BAD]Gain a Back Injury Condition[]

4.flavor=The Brotherhood of the Black Lotus has poisoned you! You fall into a coma and confront your greatest fears.
#Test Will
4.pass.flavor=You awake and feel transformed.
4.pass.info=[#GOOD]Gain a Blessed Condition[]
4.fail.flavor=The nightmares follow you into the waking world.
4.fail.info=[#BAD]Gain a Hallucinations Condition[]

5.flavor=Captain Isoge Taro of the Imperial Japanese Navy takes particular interest in your investigations. You describe the threats that the world is facing.
#Test Influence-1
5.pass.flavor=You convince him to help you.
5.pass.info=[#GOOD]One Monster of your choice\nloses three Health[]
5.fail.flavor=He is convinced that you are a dangerous menace.
5.fail.info=[#BAD]Gain a Detained Condition[]

6.flavor=The reigning Emperor has been plagued by nightmares. His advisers ask you opinion and you assure them that these horrors are real.
#Test Influence
6.pass.flavor=They Act immediately.
6.pass.info=[#GOOD]One Monster of your choice loses two Health[]
6.fail.info=[#BAD]Gain a Detained Condition[]

7.flavor=A strange man dressed in the charred robes of a monk offers you help in exchange for knowledge.
7.question=[#BAD]Spend one Clue[]?
7.pass.flavor=You convince the Black Monk to assist you.
7.pass.info=[#GOOD]Discard one Monster of your choice[]

8.flavor=A translation of The Tao of Immortality is kept in the Tokyo University Library. If you are deemed trustworthy, you are granted access to the ancient text.
#Test Influence
8.pass.flavor=You can use the arcane manual.
8.pass.info=[#GOOD]Move one Monster of your choice\nfrom any space to another space[]


9.flavor=The University allows you access to the Jigoku Zoshi, the Scroll of the Hells. You scour the text for a specific enchantment.
#Test Lore-1
9.pass.flavor=You are able to cast a dark spell on your enemies.
9.pass.info=[#GOOD]One Monster of your choice loses two Health[]
9.fail.flavor=The horrible descriptions overpower your senses.
9.fail.info=[#BAD]Lose two Sanity[]

10.flavor=Your hotel room is haunted by a yurei. You are terrified as the white-clad woman howls and passes through you.
#Test Will
10.fail.flavor=Her lingering presence is a blight on your soul.
10.fail.info.1=[#BAD]Lose one Sanity[]
10.fail.info.2=[#BAD]Gain a Cursed Condition[]

11.flavor=An old sailor struggles to remember a chant he once used to drive off a chthonian in 1923. As he mumbles, you try to identify the phrases.
#Test Lore-2
11.pass.flavor=You recognize the Vach-Viraj incantation.
11.pass.info=[#GOOD]One Monster of your choice loses two Health[]

12.flavor=You are placed on trial for violating the Peace Protection Laws.
#Test Influence
12.pass.flavor=You prove your innocence, and the government takes immediate action.
12.pass.info=[#GOOD]Discard all Monsters with one Toughness[]
12.fail.flavor=You are declared guilty.
12.fail.info=[#BAD]Gain a Detained Condition[]

13.flavor=You track down a shrine to the yato-no-kami, the gods who rule over snakes. You implore them to help you.
#Test Influence-2
13.pass.flavor=A serpent army aids you.
13.pass.info=[#GOOD]Each Monster on a space of your choice\nloses two Health[]
13.fail.flavor=Your presumptuous request earns you a snake bite.
13.fail.info=[#BAD]Gain a Poisoned Condition[]

14.flavor=You have the opportunity to display your mastery of the martial arts before karate master Gichin Funakoshi.
#Test Strength-2
14.pass.flavor=He is impressed and will instruct his students to help your cause.
14.pass.info=[#GOOD]One Monster of your choice loses two Health[]

15.flavor=You study the writings of Princess Takiyasha, hoping to master her sorcerous power.
#Test Lore-1
15.pass.flavor=You are able to summon an avenging skeleton to carry out your commands.
15.pass.info=[#GOOD]One Monster of your choice loses two Health[]
15.fail.flavor=You mistakenly summon a skeleton that attacks you.
15.fail.info.1=[#BAD]Lose one Health[]
15.fail.info.2=[#BAD]Lose one Sanity[]

16.flavor=Japanese scientists have struck a bargain with the mi-go. You try to break into one of their laboratories.
#Test Observation
16.pass.flavor=You find a radio that can control monstrous beings.
16.pass.info=[#GOOD]Discard one Monster\nwith Toughness three or less[]
16.fail.flavor=A bright light flashes and an alarm rings.
16.fail.info=[#BAD]Gain a Lost in Time and Space Condition[]

