package sk.sivak.eldritchhorror.core.view.map.investigator;

import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.math.MathUtils;
import sk.sivak.eldritchhorror.core.view.assetmanager.CustomAssetManager;
import sk.sivak.eldritchhorror.core.view.utils.FastForwardAction;

/** Map cues for investigator tokens, generated by tools/generate_travel_sounds.py. */
public final class InvestigatorSounds {

    private InvestigatorSounds() {
    }

    public static void playDepart() {
        play(CustomAssetManager.TRAVEL_DEPART_SOUND, 0.25f);
    }

    public static void playArrive() {
        play(CustomAssetManager.TRAVEL_ARRIVE_SOUND, 0.25f);
    }

    public static void playHighlight() {
        play(CustomAssetManager.INVESTIGATOR_HIGHLIGHT_SOUND, 0.25f);
    }

    private static void play(String path, float volume) {
        // Fast-forward shrinks the animations to a few frames; skip the cue instead of stacking it.
        if (FastForwardAction.isOn()) {
            return;
        }
        Sound sound = CustomAssetManager.getLoadedSound(path);
        if (sound == null) {
            sound = CustomAssetManager.getSound(path);
        }
        sound.play(volume, MathUtils.random(0.96f, 1.04f), 0f);
    }
}
